---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery需要先發現數據，以便您使用該服務。在發現過程中， NetApp Backup and Recovery會分析組織內系統中的所有磁碟區和檔案。 
---
= NetApp Backup and Recovery for SQL Server 工作負載的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用 NetApp Backup and Recovery 處理 SQL Server 工作負載之前，請先查看這些限制。



[[backup-and-recovery-preview-for-netapp-console-local-deployment-limitation]]
== NetApp Console 本機部署的 Backup and Recovery 預覽版限制

在 NetApp Console 本機部署的備份與還原預覽版本中，僅支援將備份至物件儲存的 ONTAP S3 和 StorageGRID 目標。此預覽版本不支援備份歸檔。



[[clone-lifecycle-support]]
== 克隆生命週期支援

* 不支援從物件儲存克隆。
* 按需克隆不支援批量克隆操作。
* 不支援選擇 I 組。
* 不支援選擇 QOS（最大吞吐量）選項。




[[standard-deployment-mode-only]]
== 僅限標準部署模式

此NetApp Backup and Recovery版本僅在標準部署模式下有效，不適用於受限或私有模式。



[[windows-cluster-name-restriction]]
== Windows 群集名稱限制

Windows 叢集名稱不能包含底線 (_) 字元。



[[snapcenter-migration-issues]]
== SnapCenter遷移問題

將資源從SnapCenter遷移到NetApp Backup and Recovery有以下限制。

有關SnapCenter策略如何遷移到NetApp Backup and Recovery策略的詳細信息，請參閱link:reference-policy-differences-snapcenter.html["SnapCenter中的策略與NetApp Backup and Recovery中的策略比較"]。



[[resource-group-limitations]]
=== 資源組限制

如果資源組中的所有資源都受到保護，並且其中一個資源在資源組外部也受到保護，則從SnapCenter遷移將會被阻止。

*解決方法*：在資源群組中或單獨保護資源，但不能同時保護兩者。



[[resources-with-multiple-policies-using-the-same-schedule-tier-not-supported]]
=== 不支援使用相同計劃層的多個策略的資源

您無法將使用相同排程分層（例如，每小時、每天或每週）的多個原則指派給相同資源。NetApp Backup and Recovery 不會從 SnapCenter 匯入這些資源。

*解決方法*：僅將使用相同計劃層的一項策略附加到資源。



[[hourly-policies-must-begin-at-the-start-of-the-hour]]
=== 每小時保單必須從每小時開始時開始

如果您有一個每小時重複一次但在每小時開始時不使用間隔的SnapCenter策略，NetApp Backup and Recovery將不會匯入該資源。例如，不支援1:30、2:30、3:30等時間安排的策略，但支援1:00、2:00、3:00等時間安排的策略。

*解決方法*：使用從整點開始以 1 小時為間隔重複的策略。



[[both-daily-and-monthly-policies-attached-to-one-resource-not-supported]]
=== 不支援將每日和每月策略附加到同一個資源

如果 SnapCenter 原則在日和月間隔中重複出現，NetApp Backup and Recovery 將不會匯入該原則。

例如，您無法將每日原則（間隔為 7 天或更短，或超過 7 天）附加到某個資源，同時又將每月原則附加到同一個資源。

*解決方法*：使用以每日或每月為間隔的策略，但不能同時使用兩者。



[[on-demand-backup-policies-not-migrated]]
=== 隨需備份原則未移轉

NetApp Backup and Recovery 不會從 SnapCenter 匯入隨需備份原則。



[[log-only-backup-policies-not-migrated]]
=== 僅日誌備份策略未遷移

NetApp Backup and Recovery不會從SnapCenter匯入僅日誌備份原則。如果SnapCenter策略包含僅日誌備份， NetApp Backup and Recovery將不會匯入該資源。

*解決方法*：在SnapCenter中使用不僅僅使用日誌備份的政策。



[[host-mapping]]
=== 主機映射

SnapCenter 不會將儲存叢集或儲存 VM 對應到主機，但 NetApp Backup and Recovery 會。在 NetApp Backup and Recovery 預覽版中，內部部署 ONTAP 叢集或儲存 VM 不會對應到主機。此外，NetApp Console 不支援儲存 VM。

*解決方法*：從SnapCenter匯入資源之前，請在NetApp Backup and Recovery中為在本機SnapCenter中註冊的所有本機ONTAP儲存系統建立一個系統。然後，將該叢集的資源從SnapCenter匯入NetApp Backup and Recovery。



[[schedules-not-in-15-minute-intervals]]
=== 班次間隔不為 15 分鐘

如果您有一個SnapCenter策略計劃，該計劃在特定時間啟動並以 15 分鐘間隔以外的間隔重複，NetApp Backup and Recovery將不會匯入該計劃。

*解決方法*：使用SnapCenter調整策略，使其以 15 分鐘的間隔重複。
