---
sidebar: sidebar 
permalink: br-reference-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Microsoft SQL Server database, SAP HANA database 
summary: 已知限制標識了該產品的此版本不支援的功能，或無法與其正確互通的功能。仔細審查這些限制。 
---
= NetApp Backup and Recovery for ONTAP磁碟區的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用 NetApp Backup and Recovery 備份 ONTAP 磁碟區之前，請先查看這些限制。

* NetApp Backup and Recovery可以將Cloud Volumes ONTAP備份到 AWS 中國區域（包括北京和寧夏）的物件儲存；但是，您可能需要先手動修改身分和存取策略。
+
有關在 AWS 中建立控制台代理的詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-bluexp.html["在 AWS 中安裝控制台代理"^]。

+
有關更多詳細信息，請參閱博客文章 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["NetApp Backup and Recovery功能部落格 2023 年 5 月"^]。

* NetApp Backup and Recovery不支援 Microsoft Azure 中國區域。
+
有關在 Azure 中建立控制台代理的詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-azure-bluexp.html["在 Azure 中安裝控制台代理"^]。

* NetApp Backup and Recovery不支援FlexCache磁碟區的備份。




[[replication-limitations-for-ontap-volumes]]
== ONTAP磁碟區的複製限制

* 一次只能選取一個 FlexGroup Volume 進行複寫。您需要為每個 FlexGroup Volume 分別啟動備份。
+
FlexVol® Volume 沒有此類限制：您可以選擇系統中的所有 FlexVol® Volume，並指派相同的備份原則。

* 支援以下功能 https://docs.netapp.com/us-en/data-services-replication/index.html["NetApp Replication"]，但使用NetApp Backup and Recovery的複製功能時則不然：
+
** 不支援從磁碟區 A 到磁碟區 B 以及從磁碟區 B 到磁碟區 C 的級聯設定複製。支援從卷 A 到卷 B 的複製。
** 不支援在 FSx for ONTAP系統之間複製資料。
** 不支援創建卷的一次性複製。


* 從本機ONTAP系統建立複製時，如果目標Cloud Volumes ONTAP系統上的ONTAP版本為 9.8、9.9 或 9.11，則只允許鏡像保管庫策略。
* 當您將 FlexVol 磁碟區轉換為 FlexGroup 磁碟區或反之亦然時，轉換後的磁碟區將被視為新磁碟區；您需要在轉換後為轉換後的磁碟區設定保護。您可以將轉換前建立的備份還原到不同的磁碟區。




[[backup-to-object-limitations-for-ontap-volumes]]
== ONTAP磁碟區的備份到物件限制

* 在 NetApp Console 本機部署的備份與還原預覽版本中，僅支援將備份至物件儲存的 ONTAP S3 和 StorageGRID 目標。此預覽版本不支援備份歸檔。
* 備份資料時， NetApp Backup and Recovery將不會維護NetApp磁碟區加密 (NVE)。這意味著 NVE 磁碟區上的加密資料將在資料傳輸到目標時被解密，並且加密將無法維持。
+
有關這些加密類型的說明，請參閱https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["配置NetApp卷加密概述"^]。

* 請勿備份已啟用長期保留快照的 SnapMirror 目標磁碟區。這些快照直接在目標磁碟區上建立，不會移動到物件儲存。即使之後變更 SnapMirror 原則以停用長期保留，此限制仍然有效。
* 當您建立或編輯備份策略但未向該策略指派任何磁碟區時，保留的備份數量最多可為 1018。將磁碟區指派給策略後，您可以編輯該策略以建立最多 4000 個備份。
* 備份資料保護 (DP) 磁碟區時：
+
** 具有 SnapMirror 標籤 `app_consistent` 和 `all_source_snapshot` 的關係將不會備份到雲端。
** 如果在 SnapMirror 目的地 Volume 上建立 Snapshot 的本機副本（無論 SnapMirror 使用何種標籤），這些 Snapshot 將不會作為備份移至雲端。您必須在來源 DP Volume 上建立具有所需標籤的 Snapshot 原則，以便 NetApp Backup and Recovery 可以備份這些 Snapshot。


* FlexGroup Volume 備份無法移至歸檔儲存設備。
* 如果叢集運作的是ONTAP 9.13.1 或更高版本， FlexGroup磁碟區備份可以使用 DataLock 和勒索軟體保護。
* SVM-DR 磁碟區備份受下列限制支援：
+
** 僅支援從ONTAP輔助節點進行備份。
** 應用於磁碟區的快照策略必須是NetApp Backup and Recovery可識別的策略之一，包括每日、每週、每月等。預設的「sm_created」策略（用於*鏡像所有快照*）無法識別，且 DP 磁碟區不會顯示在可備份的磁碟區清單中。
** 當備份來自來源或目的地時，SVM-DR 和 Volume 備份與還原完全獨立運作。唯一的限制是 SVM-DR 不會複寫 SnapMirror 雲端關係。在災難復原場景中，當儲存 VM 在輔助位置線上時，您必須手動更新 SnapMirror 雲端關係。


* MetroCluster支援：
+
** 當您使用 ONTAP 9.12.1 GA 或更高版本時，連接到主要系統即可支援備份。所有備份組態都會傳輸到二線系統，以便在切換後自動繼續進行雲端備份。您無需在二線系統上設定備份（實際上，您也無法這樣做）。
** 當您使用ONTAP 9.12.0 及更早版本時，僅支援從ONTAP輔助系統進行備份。
** 從 ONTAP 9.18.1 開始，FlexGroup 磁碟區備份已支援於 MetroCluster 組態中。


* 資料保護 Volume 不支援使用「立即備份」按鈕進行臨時 Volume 備份。
* 不支援 SM-BC 配置。
* ONTAP 不支援從單一 Volume 將 SnapMirror 關係連出至多個物件存放區；因此，NetApp Backup and Recovery 不支援此組態。
* 目前，Amazon S3、Google Cloud Platform（GCP）、Azure 和 StorageGRID 均支援物件儲存上的 WORM／合規模式。這稱為 DataLock 功能，必須透過 NetApp Backup and Recovery 設定來管理，而不是透過雲端供應商介面。




[[restore-limitations-for-ontap-volumes]]
== ONTAP磁碟區的還原限制

這些限制適用於恢復文件和資料夾的搜尋和恢復方法以及瀏覽和恢復方法；除非特別指出。

* 不支援從本機 Snapshot 還原資料夾。
* 在災難復原（DR）設定中還原檔案和資料夾：故障轉移後、為 DR 設定的儲存 VM 上的磁碟區會以中斷狀態保留既有的 SnapMirror 關係。由於目的地磁碟區已有關係、因此 ONTAP 會封鎖嘗試還原會建立暫時性 SnapMirror RST 關係的檔案或資料夾。
* 瀏覽和恢復一次最多可以恢復 100 個單獨的檔案。
* 搜尋和恢復功能一次只能還原一個檔案。
* 使用ONTAP 9.13.0 或更高版本時，「瀏覽和還原」和「搜尋和還原」可以還原資料夾及其內的所有檔案和子資料夾。
+
使用高於 9.11.1 但低於 9.13.0 的ONTAP版本時，還原操作只能還原選定的資料夾及其中的文件，而不會還原子資料夾或子資料夾中的檔案。

+
使用 9.11.1 之前的ONTAP版本時，不支援資料夾還原。

* 僅當叢集執行ONTAP 9.13.1 及更高版本時，才支援對駐留在檔案儲存中的資料進行目錄/資料夾還原。
* 僅當叢集執行ONTAP 9.13.1 及更高版本時，才支援使用 DataLock 保護的資料的目錄/資料夾還原。
* 正在復原的檔案必須使用與目標磁碟區上的語言相同的語言。如果語言不一樣，您將收到一條錯誤訊息。
* 將資料從 Azure 檔案儲存還原到StorageGRID系統時，不支援「高」還原優先權。
* 如果您備份了 DP 卷，然後決定中斷與該卷的SnapMirror關係，則無法將檔案還原到該卷，除非您也刪除SnapMirror關係或反轉SnapMirror方向。
* 快速恢復限制：
+
** 目標位置必須是使用ONTAP 9.13.0 或更高版本的Cloud Volumes ONTAP系統。
** 它不支援位於存檔儲存中的備份。
** 僅當建立雲端備份的來源系統執行ONTAP 9.12.1 或更高版本時，才支援FlexGroup磁碟區。
** 只有在建立雲端備份的來源系統運行ONTAP 9.11.0 或更高版本時，才支援SnapLock磁碟區。






[[enabling-indexing-in-a-disaster-recovery-configuration]]
== 在災難復原配置中啟用索引

在災難復原 (DR) 配置中，當在儲存虛擬機器叢集上啟用索引時，會出現一個錯誤，指出在配置為 Vserver DR 目標的 Vserver 上不允許執行此操作。儘管出現此錯誤，後端程序仍會將 `snapdiff-rpc-server`狀態設為「開啟」以用於來源儲存虛擬機器。儲存虛擬機器 DR 策略計畫運作後，此狀態會傳播到目標儲存虛擬機器。

*因應措施*：等待儲存 VM DR 原則排程在初始錯誤後執行，然後再次嘗試啟用索引。
