---
sidebar: sidebar 
permalink: br-start-configure-oracle-database.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle, configure 
summary: 在 NetApp Backup and Recovery 中設定您的 Oracle 資料庫。 
---
= 在 NetApp Backup and Recovery 中設定 Oracle 資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
更改獨立式或叢集式 Oracle 資料庫的驗證和節點設定。NetApp Backup and Recovery 無需這些變更即可保護資料庫，但如果在探索後環境發生變化，則可能需要更新設定。

*必要的 NetApp Console 角色* Backup and Recovery 超級管理員。了解相關資訊 link:reference-roles.html["備份與恢復角色及權限"] 和  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console 所有服務的存取角色"^]。



[[configure-an-oracle-database]]
== 設定 Oracle 資料庫

變更獨立或叢集式 Oracle 資料庫的組態。

.步驟
. 從NetApp Console選單中，選擇「保護」>「備份和復原」。
. 在“工作負載”下，選擇“Oracle”磁貼。
. 在 Oracle 清單中，選擇 *Databases* 選單。
. 在資料庫清單中，針對要設定的資料庫選取 *Configure database*（獨立式）或 *Configure RAC database*（叢集）。
. *設定資料庫設定*：設定獨立式資料庫或叢集資料庫的驗證設定。
+
** 選擇 *OS authentication* 僅使用主機作業系統進行驗證。NetApp Backup and Recovery 使用您在探索期間指定的主機認證資料。
** 當資料庫需要憑證時，請選擇 *Database authentication*。然後選擇現有憑證或新增憑證，並選擇用於連線的連接埠。


. *設定 RMAN 目錄*：選擇在保護原則中啟用自動編目或手動編目還原點時，此資料庫或叢集的備份和還原作業的中繼資料儲存位置：
+
** 選擇 *Target control file* 以將中繼資料儲存在資料庫目標控制檔案中。
** 選擇 *Catalog database* 以將中繼資料儲存在 RMAN 復原目錄中。選擇憑證和 Transparent Network Substrate (TNS) 名稱以連接到復原目錄。
+
RMAN 恢復目錄是一個獨立的資料庫綱要，RMAN 公用程式使用它來儲存已註冊資料庫的備份與恢復中繼資料。如果目標控制檔遺失或需要歷史資料，它可以提供備援和長期保留。啟用此選項會將資料檔案和歸檔日誌副本註冊到 RMAN 儲存庫中，以便 RMAN 可以追蹤和管理它們，用於報告和恢復。



. *Configure nodes*（僅限叢集資料庫）：使用箭頭按鈕新增或刪除受保護的節點，或變更節點優先權。
+
優先順序較高的節點優先受到保護。只有當優先順序較高的節點無法存取或故障時，優先順序較低的節點才會受到保護。

. 完成後，請選取 *Done* 。


.結果
Backup and Recovery 使用新設定連線至資料庫。
