---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: 如果您只是想快速找到問題的答案，此常見問題解答可以為您提供協助。 
---
= NetApp Backup and Recovery常見問題解答
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想快速找到問題的答案，此常見問題解答可以為您提供協助。



== 部署

*您需要許可證才能使用NetApp Backup and Recovery預覽版嗎？ *

您可以使用以下許可證類型：

* 註冊 30 天免費試用。


*如何啟用NetApp Backup and Recovery？ * NetApp Backup and Recovery不需要任何支援。備份和復原選項在控制台左側導覽中自動啟用。

要開始使用，您需要註冊或聯絡您的NetApp銷售代表來試用備份和復原。然後，當您使用控制台代理時，它將包含適合該服務的功能。

若要開始使用NetApp Backup and Recovery，請從其初始登入頁面選擇「開始發現工作負載」。

* NetApp Backup and Recovery是否提供標準、限制和私有模式？ *目前， NetApp Backup and Recovery僅在標準模式下可用。敬請關注。

有關所有NetApp資料服務中這些模式的說明，請參閱 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console部署模式"^]。



== 使用權

* NetApp Backup and RecoveryURL 是什麼？ *對於 URL，在瀏覽器中輸入： https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^]存取NetApp Console。

*如何處理存取權限？ *只有組織管理員才有能力啟動服務並發現工作負載（因為這涉及承諾使用資源）。後續互動可以由任何角色完成。

*什麼設備解析度最好？ *NetApp Backup and Recovery的建議設備解析度為 1920x1080 或更高。

*我該使用哪種瀏覽器？ *任何現代瀏覽器都可以使用。



== 與其他服務的交互

* NetApp Backup and Recovery是否知道NetApp ONTAP中所做的保護設定？ *是的， NetApp Backup and Recovery發現了在ONTAP中設定的快照計畫。

*如果您使用NetApp Backup and Recovery設定策略，那麼將來是否只需在備份和復原中進行變更？ *我們建議您從NetApp Backup and Recovery進行策略變更。



== 工作負載

*工作量由什麼組成？ *工作負載是 2025 預覽版的應用程式。工作負載包括單一應用程式執行個體所使用的所有磁碟區。例如，部署在 mssql3.host.com 上的 Microsoft SQL Server DB 執行個體可以分別使用 vol1 和 vol2 來儲存其資料和日誌。這些磁碟區共同構成了資料庫執行個體的特定執行個體的工作負載。

* NetApp Backup and Recovery支援哪些工作負載？ *

對於預覽版 2025， NetApp Backup and Recovery可以辨識下列工作負載：Microsoft SQL Server 應用程式。

*什麼是「受保護」的工作負載？ *在NetApp Backup and Recovery中，當啟用主要偵測策略時，工作負載將顯示「受保護」狀態。

*什麼是「有風險」的工作負載？ *如果工作負載沒有啟用主要偵測策略，那麼即使啟用了備份和快照策略，它仍然「處於危險之中」。

*新增了新的工作負載，但尚未出現* 如果您在環境中新增了新的工作負載，請再次啟動發現並套用保護策略來保護該新資源。



== 保護策略

* NetApp Backup and Recovery是否知道NetApp ONTAP中所做的保護設定？ *

是的， NetApp Backup and Recovery會發現在ONTAP中設定的快照計畫以及在發現的工作負載中是否啟用了 ARP 和 FPolicy。您最初在儀表板中看到的資訊是從其他NetApp解決方案和產品匯總而來的。

* NetApp Backup and Recovery是否知道SnapCenter中已經制定的策略？ *

是的，如果您在SnapCenter中管理工作負載，則這些產品管理的策略將納入NetApp Backup and Recovery。

*您可以修改從SnapCenter繼承的策略嗎？ *

是的，您可以修改NetApp Backup and Recovery中由SnapCenter管理的策略。

*如果ONTAP中存在策略（已在系統管理員中啟用，例如 ARP、FPolicy 和快照），那麼這些策略是否會在NetApp Backup and Recovery中發生變更？ *

不會。 NetApp NetApp Backup and Recovery不會修改ONTAP中的任何現有偵測策略（ARP、FPolicy 設定）。

*註冊NetApp Backup and Recovery後，如果在SnapCenter中新增政策會發生什麼情況？ *

NetApp Backup and Recovery可辨識在SnapCenter中建立的任何新政策。

*您可以從ONTAP更改策略嗎？ *

是的，您可以在NetApp Backup and Recovery中從ONTAP更改策略。您也可以在NetApp Backup and Recovery中建立新策略並將其套用至工作負載。此操作將使用在NetApp Backup and Recovery中建立的策略來取代現有的ONTAP策略。
