---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 在使用NetApp Backup and Recovery 之前，請執行幾個步驟來設定備份目標。 
---
= 在使用NetApp Backup and Recovery 之前設定備份目標
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在使用NetApp Backup and Recovery 之前，請執行幾個步驟來設定備份目標。

在開始之前，請查看link:concept-start-prereq.html["先決條件"]以確保您的環境已準備就緒。



== 準備備份目標

準備以下一個或多個備份目標：

* NetAppStorageGRID。
+
參考 https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["了解StorageGRID"^]。

+
參考 https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID文檔"^]有關StorageGRID的詳細資訊。

* 亞馬遜網路服務。參考 https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Amazon S3 文檔"^]。
+
執行下列操作以準備將 AWS 作為備份目標：

+
** 在 AWS 中設定一個帳戶。
** 在 AWS 中配置 S3 權限，列於下一節。
** 有關在控制台中管理 AWS 儲存的詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["管理您的 Amazon S3 儲存桶"^]。




* 微軟 Azure。
+
** 參考 https://docs.netapp.com/us-en/storage-management-azure-netapp-files/index.html["Azure NetApp Files文檔"^]。
** 在 Azure 中設定一個帳戶。
** 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 權限"^]在 Azure 中。
** 有關在控制台中管理 Azure 儲存體的詳細信息，請參閱 https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["管理 Azure 儲存體帳戶"^]。




在備份目標本身配置選項後，您稍後會將其配置為NetApp Backup and Recovery 中的備份目標。有關如何在NetApp Backup and Recovery 中配置備份目標的詳細信息，請參閱link:br-start-discover-backup-targets.html["發現備份目標"]。



== 設定 S3 權限

您需要設定兩組 AWS S3 權限：

* 控制台代理程式建立和管理 S3 儲存桶的權限。
* 本地ONTAP叢集的權限，以便它可以讀取和寫入 S3 儲存桶的資料。


.步驟
. 確保控制台代理具有所需的權限。有關詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["NetApp控制台策略權限"]。
+

NOTE: 在 AWS 中國區域建立備份時，您需要將 IAM 政策中所有_Resource_部分下的 AWS 資源名稱「arn」從「aws」變更為「aws-cn」；例如 `arn:aws-cn:s3:::netapp-backup-*`。

. 當您啟動服務時，備份精靈會提示您輸入存取金鑰和金鑰。這些憑證會傳遞到ONTAP集群，以便ONTAP可以將資料備份和還原到 S3 儲存桶。為此，您需要建立具有以下權限的 IAM 使用者。
+
請參閱 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS 文件：建立角色以將權限委託給 IAM 用戶"^]。

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

