---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 準備一個異地位置，例如 StorageGRID、AWS 或 Azure，並設定所需的權限，使其可以用作備份目的地。 
---
= 設定備份目的地
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
準備一個異地位置，例如 StorageGRID、AWS 或 Azure，並設定所需的權限，使其可以用作備份目的地。

在開始之前，請查看link:concept-start-prereq.html["先決條件"]以確保您的環境已準備就緒。



[[prepare-the-backup-destination]]
== 準備備份目標

準備以下一個或多個備份目標：

* NetAppStorageGRID。
+
請參閱 https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["了解StorageGRID"^]。

+
如需有關 StorageGRID 的詳細資訊，請參閱 https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID文檔"^]。

* Amazon Web Services。參見 https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Amazon S3 文檔"^]。
+
執行下列操作以準備將 AWS 作為備份目標：

+
** 在 AWS 中設定一個帳戶。
** 在 AWS 中配置 S3 權限，列於下一節。
** 有關在 Console 中管理 AWS 儲存設備的詳細資訊，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["管理您的 Amazon S3 儲存桶"^]。


* 微軟 Azure。
+
** 請參閱 https://docs.netapp.com/us-en/storage-management-blob-storage/index.html["Azure Blob 儲存設備文件"^]。
** 在 Azure 中設定一個帳戶。
** 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 權限"^]在 Azure 中。
** 有關在 Console 中管理 Azure 儲存設備的詳細資訊，請參閱 https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["管理 Azure 儲存體帳戶"^]。




在備份目的地本身設定好選項後，稍後您需要在 NetApp Backup and Recovery 中將其設定為備份目的地。有關如何在 NetApp Backup and Recovery 中設定備份目的地的詳細資訊，請參閱 link:br-start-discover-backup-targets.html["發現備份目標"]。



[[set-up-s3-permissions]]
== 設定 S3 權限

您需要設定兩組 AWS S3 權限：

* 控制台代理程式建立和管理 S3 儲存桶的權限。
* 本地ONTAP叢集的權限，以便它可以讀取和寫入 S3 儲存桶的資料。


.步驟
. 確保控制台代理具有所需的權限。有關詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["NetApp Console策略權限"]。
+

NOTE: 在 AWS 中國區域建立備份時，您需要將 IAM 政策中所有_Resource_部分下的 AWS 資源名稱「arn」從「aws」變更為「aws-cn」；例如 `arn:aws-cn:s3:::netapp-backup-*`。

. 當您啟動服務時，備份精靈會提示您輸入存取金鑰和金鑰。這些憑證會傳遞到ONTAP集群，以便ONTAP可以將資料備份和還原到 S3 儲存桶。為此，您需要建立具有以下權限的 IAM 使用者。
+
請參閱  https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS 文件：建立角色以將權限委託給 IAM 用戶"^]。

+
[%collapsible]
====
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "s3:PutEncryptionConfiguration"
      ],
      "Resource": "arn:aws:s3:::netapp-backup-*",
      "Effect": "Allow",
      "Sid": "backupPolicy"
    },
    {
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListAllMyBuckets",
        "s3:PutObjectTagging",
        "s3:GetObjectTagging",
        "s3:RestoreObject",
        "s3:GetBucketObjectLockConfiguration",
        "s3:GetObjectRetention",
        "s3:PutBucketObjectLockConfiguration",
        "s3:PutObjectRetention"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*/*",
      "Effect": "Allow"
    }
  ]
}
----
====

