---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery 需要先發現工作負載，以便您使用該服務。 
---
= 探索NetApp備份與復原中的 Kubernetes 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 需要先發現 Kubernetes 工作負載，以便您使用該服務。

*所需的NetApp控制台角色* 備份和還原超級管理員。了解link:reference-roles.html["備份和恢復角色和權限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp控制台存取角色"^] 。



== 發現 Kubernetes 工作負載

在備份和復原清單中，您可以發現環境中正在執行的 Kubernetes 工作負載。發現工作負載會將 Kubernetes 叢集新增至NetApp備份和復原中，使您能夠將應用程式新增至叢集並保護叢集託管的資源。

.步驟
. 執行下列操作之一：
+
** 如果您是第一次發現 Kubernetes 工作負載，請在NetApp Backup and Recovery 中選擇 Kubernetes 工作負載類型下的 *Discover and Manage*。
** 如果您已經發現 Kubernetes 工作負載，請在NetApp Backup and Recovery 中選擇 *Inventory* > *Workloads*，然後選擇 *Discover resources*。


. 選擇 *Kubernetes* 工作負載類型。
. 輸入叢集名稱並選擇與叢集一起使用的連接器。
. 按照出現的命令列說明進行操作：
+
** 建立Trident保護命名空間
** 建立 Kubernetes 機密
** 新增 Helm 儲存庫
** 安裝Trident Protect 和Trident Protect 連接器
+
這些步驟確保NetApp Backup and Recovery 可以與叢集互動。



. 完成這些步驟後，選擇*發現*。
+
該集群已新增至清單。

. 在關聯的 Kubernetes 工作負載中選擇「檢視」以查看該工作負載的應用程式、叢集和命名空間清單。




== 繼續存取NetApp備份和還原儀表板

若要顯示NetApp備份和還原儀表板，請依照下列步驟操作。

. 從頂部選單中選擇*儀表板*。
. 檢討資料保護的健康狀況。處於危險中或受保護的工作負載的數量會根據新發現、受保護和備份的工作負載而增加。
+
link:br-use-dashboard.html["了解儀表板顯示的內容"] 。


