---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery需要先發現工作負載，以便您使用該服務。 
---
= 探索NetApp Backup and Recovery中的 Kubernetes 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 NetApp Backup and Recovery 中探索 Kubernetes 叢集及其工作負載，以便使用保護原則加以保護。

*必要的 NetApp Console 角色* 備份與還原超級管理員。如果您要保護儲存在 Cloud Volumes ONTAP 叢集上的資料，則還需要 Cloud Volumes ONTAP 管理員角色。了解link:reference-roles.html["備份和恢復角色和權限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp Console存取角色"^]。



[[discover-kubernetes-workloads]]
== 發現 Kubernetes 工作負載

在備份與還原清單中，探索環境中的 Kubernetes 叢集和工作負載。新增叢集後，您可以將其註冊到 NetApp Backup and Recovery 中，並探索其應用程式和資源以進行保護。您也可以選擇使用 NetApp Console 本機部署來探索與外部網路隔離的本機 Kubernetes 資源。

[NOTE]
====
當您探索目前受 Trident Protect 保護的叢集時，由於 Trident Protect 備份排程與備份與還原不相容，因此在探索過程中，所有與 Trident Protect 搭配使用的備份排程都會停用。若要保護叢集的應用程式，link:br-use-policies-create.html["建立新的保護原則"]或將應用程式與現有原則建立關聯。您可以視需要移除 Trident Protect 備份排程。

====
.步驟
. 執行下列操作之一：
+
** 如果您是第一次發現 Kubernetes 工作負載，請在NetApp Backup and Recovery中，在「工作負載」下，選擇「Kubernetes」磁貼。
** 如果您已經發現 Kubernetes 工作負載，請在NetApp Backup and Recovery中選擇 *Inventory* > *Workloads*，然後選擇 *Discover resources*。


. 選擇 *Kubernetes* 工作負載類型。
. 輸入叢集名稱並選擇要與叢集搭配使用的 Console 代理程式。
+
備份與還原提供的說明會根據您選擇的安裝類型而變更。如果您使用 NetApp Console 本機部署，則可以選擇用於探索與外部網路連線不相連的氣隙資源的說明。

. 選擇安裝類型以檢視在 Kubernetes 叢集上安裝 Trident Protect 的說明：
+
** 選擇「已連線」以探索具有外部網路連線的叢集。
** 選擇 *Air-gapped* 以探索沒有外部網路連線的叢集。
+
[role="tabbed-block"]
====
.連線探索
--
... 請依照 Backup and Recovery 中顯示的命令列說明進行操作。這些步驟可確保 Backup and Recovery 能夠與叢集互動。


--
.Air-gapped 探索
--
... 輸入您的私人 Docker Container 登錄的 URL。安裝過程中，將使用此登錄下載 Trident Protect 和 Trident Protect Connector "映像"。
... 如果您的私有 Container 登錄需要驗證，請使用下列其中一種方法來設定登錄認證：
+
**** *節點層級驗證*：在每個節點的 Container 執行階段中設定登錄憑證。設定完成後，所有 Pod 均可提取"映像"，無需額外的 Helm 設定。
**** *Kubernetes image pull secret*：在 `trident-protect`命名空間中建立 Kubernetes image pull secret，然後在 Trident Protect 安裝說明中的 Helm 升級步驟中引用它：
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... 請依照 Backup and Recovery 中顯示的命令列說明進行操作，並在 Helm 步驟中新增"映像"拉取金鑰資訊（如果需要）。這些步驟可確保 Backup and Recovery 能夠與叢集互動。


--
====


. 完成 Trident Protect 安裝步驟後，選取 * 探索 *。
+
該集群已新增至清單。

. 在關聯的 Kubernetes 工作負載中選擇「檢視」以查看該工作負載的應用程式、叢集和命名空間清單。




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== 繼續存取NetApp Backup and Recovery儀表板

請按照以下步驟檢視 NetApp 備份與還原儀表板並驗證已探索的資源。

. 從NetApp Console選單中，選擇 *保護* > *備份和還原*。
. 選擇 Kubernetes 工作負載磁貼。
. 從備份和還原選單中，選擇*儀表板*。
. 檢討資料保護的健康狀況。處於危險中或受保護的工作負載的數量會根據新發現、受保護和備份的工作負載而增加。
+
link:br-use-dashboard.html["了解儀表板顯示的內容"]。


