---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: 向您的雲端供應商購買隨用隨付或年度市場訂閱，或向 NetApp 購買自帶授權，以授權 NetApp Backup and Recovery。 
---
= 設定NetApp Backup and Recovery 的許可
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
透過 NetApp 市場訂閱或自帶授權 （BYOL），在 NetApp Console 或 NetApp Console 本機部署中設定 NetApp Backup and Recovery 的授權。需要有效的授權才能啟動服務、建立備份，以及將資料還原至正式作業系統。

關於授權運作方式的幾點說明：

* 使用 ONTAP Volumes 工作負載時，無需授權即可探索和還原磁碟區。但是，如果需要保護（備份）磁碟區，則需要購買授權。
* 如果您正在搭配 NetApp Console 本機部署使用 Backup and Recovery，則只能購買自備授權（BYOL）授權。
* NetApp Backup and Recovery自帶許可證 (BYOL) 是一種浮動許可證，您可以在與NetApp Console組織或帳戶關聯的所有系統中使用它。因此，如果您現有的 BYOL 授權具有足夠的備份容量，則無需購買另一個 BYOL 授權。
* 如果您使用自帶授權 （BYOL） 授權搭配 NetApp Console，建議您同時訂閱隨用隨付 （PAYGO） 訂閱。如果您備份的資料超過 BYOL 授權允許的範圍，或您的授權到期，備份將繼續透過您的隨用隨付 （PAYGO） 訂閱進行，服務不會中斷。
* 將內部部署 ONTAP 資料備份到 StorageGRID 時，您需要 BYOL 授權，但雲端供應商儲存空間是免費的。


link:concept-backup-to-cloud.html["了解有關使用NetApp Backup and Recovery 的成本的更多資訊。"]



[[licensing-options-for-netapp-backup-and-recovery]]
== NetApp 備份與還原的授權選項

NetApp Backup and Recovery 有三種授權選項：

* 直接從 NetApp 購買授權，也稱為自帶授權 (BYOL)。此選項適用於 NetApp Console 和 Console 本地部署。
* 從大型公有雲市場購買年度合約。此選項僅適用於 NetApp Console。
* 從大型公有雲市場訂閱隨用隨付 （PAYGO） 授權。此選項僅適用於 NetApp Console。




[[30-day-free-trial]]
=== 30天免費試用

除 ONTAP Volumes 工作負載外，所有未授權工作負載均可享有 30 天的 NetApp Backup and Recovery 免費試用。您可以在開始使用工作負載時（在探索其資源之前）啟動試用。試用開始後，其狀態和已使用容量將顯示在 NetApp Backup and Recovery 首頁的 *Free Trials* 下方。



==== 結束免費試用

您可以隨時從登入 NetApp Backup and Recovery 後顯示的首頁結束工作負載的免費試用。如果您想在免費試用結束後繼續使用 NetApp Backup and Recovery，則必須在 NetApp Console 介面的 *Licenses and subscriptions* 部分設定付費訂閱。如果您不想繼續使用 NetApp Backup and Recovery，可以在不訂閱付費方案的情況下結束免費試用。您可以link:prev-ontap-backup-manage.html["從系統取消註冊NetApp Backup and Recovery"]在試用期結束前結束試用，且不會被收取任何費用。

.步驟
. 在 NetApp Backup and Recovery 首頁的 *Free trials* 下，選擇您要結束的免費試用。
. 選擇*結束免費試用*。
. 在框框中輸入*結束試用*。
. 選擇 *End trial* 進行確認。




[[use-a-byol-license]]
=== 使用自備授權 (BYOL)

NetApp提供的自備授權的有效期限為 1 年、2 年或 3 年。您只需為您保護的資料付費，該費用根據正在備份的來源ONTAP磁碟區的邏輯使用容量（任何效率之前）計算。此容量也稱為前端兆位元組 (FETB)。

BYOL NetApp Backup and Recovery許可證是一種浮動許可證，其總容量在與您的NetApp Console組織或帳戶關聯的所有系統之間共用。對於ONTAP系統，您可以透過執行 CLI 命令來粗略估計所需的容量 `volume show -fields logical-used-by-afs`對於您計劃備份的磁碟區。

如果您沒有 NetApp Backup and Recovery BYOL 授權，請選擇 Console 右下角的聊天圖示進行購買。

或者，如果您擁有未指派的基於節點的Cloud Volumes ONTAP授權但不會使用，則可以將其轉換為具有相同美元等值和相同到期日的NetApp Backup and Recovery授權。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["點此了解詳情"^] 。

您可以使用 NetApp Console 或 NetApp Console 本機部署來管理自帶授權 （BYOL） 授權。您可以從 Console 新增授權、更新現有授權，以及檢視授權狀態。

https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html["了解如何新增許可證"^]。



[[use-a-marketplace-license-applies-to-netapp-console-only]]
=== 使用市場授權（僅適用於 NetApp Console）

透過購買年度合約每年支付NetApp Backup and Recovery的費用。期限分為 1 年、2 年或 3 年。

如果您與市場平台簽訂了年度合約，則所有 NetApp Backup and Recovery 的使用費用都將計入該合約。

當您使用 AWS 時，有兩種年度合約可供選擇 https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWS Marketplace 頁面"^]對於Cloud Volumes ONTAP和本機ONTAP系統：

* 「雲端備份」計畫可讓您備份Cloud Volumes ONTAP資料和本機ONTAP資料。
+
如果您想使用此選項，請從 Marketplace 頁面設定您的訂閱，然後 https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["將訂閱與您的 AWS 憑證關聯"^]。請注意，您還需要使用此年度合約訂閱來支付您的Cloud Volumes ONTAP系統的費用，因為您只能在控制台中為您的 AWS 憑證指派一個有效訂閱。

* 「CVO Professional」計畫可讓您捆綁Cloud Volumes ONTAP和NetApp Backup and Recovery。這包括使用許可證對Cloud Volumes ONTAP系統進行無限制備份（備份容量不計入許可容量）。此選項不允許您備份本機ONTAP資料。
+
查看 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP授權主題"^]了解有關此許可選項的更多資訊。

+
如果您想使用此選項，可以在建立Cloud Volumes ONTAP系統時設定年度合同，控制台會提示您訂閱 AWS Marketplace。



使用 Azure 時，有兩種年度合約可從 https://marketplace.microsoft.com/en-us/product/netapp.netapp-bluexp["Azure 市集頁面"^]取得，分別適用於 Cloud Volumes ONTAP 和內部部署 ONTAP 系統：

* 「雲端備份」計畫可讓您備份Cloud Volumes ONTAP資料和本機ONTAP資料。
+
如果您想使用此選項，請從 Marketplace 頁面設定您的訂閱，然後 https://docs.netapp.com/us-en/console-setup-admin/task-adding-azure-accounts.html#subscribe["將訂閱與您的 Azure 憑證關聯"^]。請注意，您還需要使用此年度合約訂閱來支付您的Cloud Volumes ONTAP系統的費用，因為您只能在控制台中為您的 Azure 憑證指派有效訂閱。

* 「CVO Professional」計畫可讓您捆綁Cloud Volumes ONTAP和NetApp Backup and Recovery。這包括使用許可證對Cloud Volumes ONTAP系統進行無限制備份（備份容量不計入許可容量）。此選項不允許您備份本機ONTAP資料。
+
查看 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP授權主題"^]了解有關此許可選項的更多資訊。

+
如果您想使用此選項，可以在建立Cloud Volumes ONTAP系統時設定年度合同，控制台會提示您訂閱 Azure Marketplace。



當您使用 GCP 時，請聯絡您的NetApp銷售代表購買年度合約。該合約在 Google Cloud Marketplace 中以私人優惠形式提供。

NetApp提供您專屬優惠後，您可以在啟動NetApp Backup and Recovery時透過 Google Cloud Marketplace 訂閱並選擇年度方案。



[[use-a-netapp-backup-and-recovery-paygo-subscription-applies-to-netapp-console-only]]
=== 使用 NetApp Backup and Recovery 隨用隨付訂閱（僅適用於 NetApp Console）

對於隨用隨付，您可以在單一訂閱中，按小時向您的雲端供應商支付物件儲存成本和 NetApp 備份授權成本。即使您使用的是免費試用版或自備授權 （BYOL），您也應該在市場中訂閱 *NetApp Intelligent Services*：

* 訂閱可確保免費試用結束後服務不會中斷。試用期結束後，我們將根據您備份的資料量按小時向您收費。
* 如果您備份的資料超出了 BYOL 授權允許的範圍，則資料備份和復原作業將透過即用即付訂閱繼續進行。例如，如果您擁有 10 TiB BYOL 許可證，則超過 10 TiB 的所有容量都將透過 PAYGO 訂閱收費。


在免費試用期間或未超出 BYOL 授權的情況下，您無需支付即用即付訂閱費用。

NetApp Backup and Recovery有幾種 PAYGO 計畫：

* 「雲端備份」套件可讓您備份Cloud Volumes ONTAP資料和本機ONTAP資料。
* “CVO Professional” 軟體包可讓您捆綁Cloud Volumes ONTAP和NetApp Backup and Recovery。這包括使用許可證對Cloud Volumes ONTAP系統進行無限制備份（備份容量不計入許可容量）。此選項不允許您備份本機ONTAP資料。
+
此選項也需要備份與還原隨用隨付訂閱，但符合資格的 Cloud Volumes ONTAP 系統不會產生費用。



https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["了解有關這些基於容量的許可證包的更多信息"]。

使用這些連結從您的雲端供應商市場訂閱NetApp Backup and Recovery ：

* AWS： https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["前往NetApp Intelligent Services市場了解定價詳情"^] 。
* Azure： https://marketplace.microsoft.com/en-us/product/netapp.cloud-manager?tab=Overview["前往NetApp Intelligent Services市場了解定價詳情"^]。
* Google Cloud： https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["前往NetApp Intelligent Services市場了解定價詳情"^] 。




[[exceeding-license-capacity]]
== 超出授權容量

超出授權容量將觸發隨用隨付 （PAYGO） 費率。如果沒有隨用隨付訂閱，您將無法建立新的備份，但仍可還原現有備份，只是服務品質無法保證。請在授權到期前續訂，因為過期的授權會阻止建立新的備份並中斷服務。



[[what-happens-when-your-license-expires]]
== 授權到期後會發生什麼情況

當您的 Backup and Recovery 授權到期時：

* 根據現有備份策略進行的備份和還原作業仍然有效。
* 您無法建立新的備份原則，也無法將保護擴展至其他工作負載和資料存放區。
* 您無法使用新的 Backup and Recovery 功能及增強功能。
* NetApp 備份和復原的技術支援已不再提供。


續訂您的授權：

* 建立和修改備份策略，包括資料庫、虛擬機器和 Kubernetes 工作負載的應用程式一致性備份策略。
* 使用新的備份和復原功能及增強功能。
* 繼續獲取 NetApp 技術支援。

