---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery必須先發現 Hyper-V 虛擬機，然後您才能保護它們。 
---
= 在NetApp Backup and Recovery中發現 Hyper-V 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 NetApp Backup and Recovery 中探索 Hyper-V 虛擬機器，以便使用保護原則來保護它們。

*必要的 NetApp Console 角色* 備份與還原超級管理員。了解 link:reference-roles.html["備份與恢復角色及權限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp Console存取角色"^]。



[[add-a-hyper-v-host-and-discover-resources]]
== 新增 Hyper-V 主機並發現資源

新增 Hyper-V 主機資訊，以便 NetApp 備份與還原功能探索虛擬機器。在每個 Console 代理程式中，選擇要探索資源的系統。


NOTE: 當您新增 Hyper-V 主機並發現資源時， NetApp Backup and Recovery會在 Hyper-V 主機上安裝NetApp Hyper-V 插件和NetApp SnapCenter Windows FileSystem 插件，以協助管理和保護虛擬機器。

.步驟
. 從 NetApp Console 選單中，選取 *Protection* > *Backup and Recovery*。
+
如果您是第一次登入 NetApp Backup and Recovery，且已在 Console 中擁有系統但尚未探索資源，則會顯示「歡迎使用新的 NetApp Backup and Recovery」活動網頁，其中包含 *探索資源* 選項。

. 選擇*發現資源*。
. 輸入以下資訊：
+
.. *工作負載類型*：選擇*Hyper-V*。
.. 如果您尚未儲存此 Hyper-V 主機的憑證，請選擇「新增憑證」。
+
... 選擇與該主機一起使用的控制台代理程式。
... 輸入此憑證的名稱。
... 輸入該帳戶的使用者名稱和密碼。
... 選擇*完成*。


.. *主機註冊*：透過輸入主機的 FQDN 或 IP 位址、憑證、控制台代理程式和連接埠號碼來新增新的 Hyper-V 主機。如果控制台代理無法解析 FQDN，則改用 IP 位址。對於 FCI 集群，請輸入 FCI 集群管理 IP 位址。


. 選擇*發現*。
+

TIP: 此過程可能需要幾分鐘。



.結果
NetApp Backup and Recovery發現資源後，「清單」頁面會在工作負載清單中顯示 Hyper-V 工作負載。



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== 繼續存取NetApp Backup and Recovery儀表板

.步驟
. 從 NetApp Console 選單中，選取 *Protection* > *Backup and Recovery*。
. 選擇 Hyper-V 工作負載磁貼。
. 從備份和還原選單中，選擇*儀表板*。
. 檢討資料保護的健康狀況。處於危險中或受保護的工作負載的數量會根據新發現、受保護和備份的工作負載而增加。

