---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: '您可以從 Windows 用戶作業系統上的虛擬機器磁碟 (VMDK) 還原檔案或資料夾。' 
---
= 恢復訪客文件和資料夾的要求和限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從 Windows 用戶作業系統上的虛擬機器磁碟 (VMDK) 還原檔案或資料夾。



== 來賓還原工作流程

客戶作業系統還原操作包含以下步驟：

. 附
+
將虛擬磁碟附加到客戶虛擬機器或代理虛擬機器並啟動客戶檔案復原會話。

. 等待
+
請等待附加操作完成，然後才能瀏覽和恢復。附加操作完成後，會自動建立訪客文件恢復工作階段。

. 選擇檔案或資料夾
+
瀏覽 VMDK 文件，選擇一個或多個文件或資料夾進行還原。

. 恢復
+
將選定的檔案或資料夾還原到指定位置。





== 恢復訪客文件和資料夾的先決條件

在 Windows 用戶作業系統上從 VMDK 還原檔案或資料夾之前，請檢查所有要求。

* 必須安裝並執行 VMware 工具。
+
NetApp Backup and Recovery使用 VMware 工具的資訊來建立與 VMware 客戶作業系統的連線。

* Windows 客戶作業系統必須執行 Windows Server 2008 R2 或更高版本。
+
有關受支援版本的最新信息，請參閱 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。

* 目標虛擬機器的憑證使用使用者名稱為「Administrator」的內建網域或本機管理員帳號。在開始復原作業之前，請先設定要附加虛擬磁碟的虛擬機器的憑證。附加和恢復操作都需要憑證。工作群組使用者可以使用內建的本機管理員帳戶。
+

IMPORTANT: 如果您必須使用非內建管理員帳戶但在 VM 內具有管理權限的帳戶，則必須在來賓 VM 上停用 UAC。

* 您必須知道要從中還原的備份快照和 VMDK。
+
NetApp Backup and Recovery不支援搜尋檔案或資料夾進行還原。在開始之前，您必須知道快照中的檔案或資料夾以及對應的 VMDK 的位置。

* 要附加的虛擬磁碟必須位於NetApp Backup and Recovery備份中。
+
包含要還原的檔案或資料夾的虛擬磁碟必須位於使用NetApp Backup and Recovery執行的 VM 備份中。



* 對於名稱非英文字母的文件，您必須將它們恢復到目錄中，而不是單一文件。
+
您可以透過恢復文件所在的目錄來恢復具有非字母名稱的文件，例如日語漢字。





== 來賓檔案還原限制

在從客戶作業系統還原檔案或資料夾之前，您應該了解其功能限制。

* 您無法在來賓作業系統內還原動態磁碟類型。
* 如果還原加密的檔案或資料夾，則不會保留加密屬性。您無法將檔案或資料夾還原到加密資料夾。
* 訪客文件瀏覽頁面顯示隱藏的文件和資料夾，您無法過濾。
* 您無法從 Linux 客戶作業系統復原。
+
您無法從執行 Linux 客戶作業系統的 VM 還原檔案和資料夾。但是，您可以附加 VMDK，然後手動恢復檔案和資料夾。有關受支援的客戶作業系統的最新信息，請參閱 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。

* 您無法從 NTFS 檔案系統還原到 FAT 檔案系統。
+
當您嘗試從 NTFS 格式還原為 FAT 格式時，不會複製 NTFS 安全性描述符，因為 FAT 檔案系統不支援 Windows 安全性屬性。

* 您無法從克隆的 VMDK 或未初始化的 VMDK 恢復客戶檔案。
* 您無法復原檔案的目錄結構。
+
從嵌套目錄恢復檔案時，系統只會恢復檔案本身，而不會恢復其目錄結構。若要復原整個目錄樹，請複製頂層目錄。

* 您無法將客戶檔案從 vVol VM 還原到備用主機。
* 您無法恢復加密的訪客檔案。

