---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-access-control.html 
keywords: backup, back up, restore, recovery, kubernetes, k8s, access control, rbac, iam, folder, project 
summary: 透過使用 NetApp Console 資料夾、專案和角色，管理對 NetApp Backup and Recovery 中 Kubernetes 資源的存取。 
---
= 管理 Kubernetes 資源存取
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 NetApp Backup and Recovery 中，於叢集或資源層級管理對 Kubernetes 資源的存取。您可以透過在 NetApp Console 中進行探索時將叢集與資料夾或專案建立關聯，並指派適當的角色給使用者，來管理對叢集資源的存取。透過將命名空間註冊為與專案或資料夾相關聯的 IAM 資源，來管理命名空間層級的資源存取。

有關將叢集與 IAM 資料夾或專案關聯的資訊，請參閱 link:br-start-discover-kubernetes.html["發現 Kubernetes 工作負載"]。

Kubernetes 資源的 Backup and Recovery 命名空間層級資源存取，是由您在註冊命名空間以進行存取控制時，與該命名空間關聯的資料夾或專案所控制。在命名空間與資料夾或專案關聯後，擁有該範圍適當 NetApp Console 和 Backup and Recovery 角色的使用者，即可存取該命名空間及其受保護的資源。



[[backup-and-recovery-roles-and-what-they-allow-with-kubernetes-workloads]]
== 備份與恢復角色及其對 Kubernetes 工作負載允許的操作

對於與資料夾或專案關聯的 Kubernetes 叢集或命名空間，使用者在該資料夾或專案上擁有的特定備份與恢復角色決定了他們可以執行的操作。如需有關備份與恢復角色的詳細資訊，請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console 中的備份與還原角色"^]。


NOTE: Backup and Recovery Clone 管理員角色不適用於 Kubernetes 工作負載。

[cols="1,2,2"]
|===
| 角色 | 檢視存取範圍 | 允許的動作 


| 備份和恢復超級管理員 | 全面檢視範圍內的叢集、命名空間和應用程式 | 檢視、建立應用程式、保護（建立/移除保護）和還原 


| 備份和恢復檢視器 | 僅檢視範圍內的叢集和命名空間 | 僅供檢視。無法建立、保護或還原。 


| Backup and Recovery 備份管理員 | 全面檢視範圍內的叢集、命名空間和應用程式 | 檢視、建立應用程式和保護（建立/移除保護）。無法還原。 


| 備份與恢復還原管理員 | 全面檢視範圍內的叢集、命名空間和應用程式 | 僅可檢視和還原。無法建立應用程式或保護原則。 
|===


[[associate-a-kubernetes-namespace-with-a-folder-or-project]]
== 將 Kubernetes 命名空間與資料夾或專案關聯

將命名空間與資料夾或專案建立關聯，以便存取控制適用於該範圍。

*必要的 NetApp Console 角色* 備份與還原超級管理員。如果您要保護儲存在 Cloud Volumes ONTAP 叢集上的資料，則還需要 Cloud Volumes ONTAP 管理員角色。了解link:reference-roles.html["備份和恢復角色和權限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp Console存取角色"^]。

.步驟
. 從NetApp Console選單中，選擇 *保護* > *備份和還原*。
. 在 *工作負載* 下，選擇 *Kubernetes* 圖塊。
. 在清單中，選擇 *命名空間* 選單。
. 選擇一個或多個要註冊存取控制的命名空間，並為每個命名空間啟用核取方塊。
. 選擇 *註冊存取控制*。
. （可選）選擇一個資料夾或專案，以確定此命名空間的存取控制應用範圍。如果未選擇資料夾或專案，則命名空間 IAM 資源將被註冊，但不會新增至任何資料夾或專案：
+
** *資料夾*：選擇此選項可控制使用者對資料夾層級命名空間資源的存取，並從清單中選擇資料夾。
+

NOTE: 如果 Kubernetes 叢集或命名空間與資料夾關聯，使用者還需要擁有右上角專案選擇器中所選專案的 *Backup and Recovery viewer* 角色。此專案層級存取可讓使用者開啟 Backup and Recovery 首頁。在資料夾層級指派的角色（例如 Backup and Recovery 備份管理員）決定了使用者進入工作負載頁面後可以執行的操作，但角色本身並不會授予對頁面的存取。

** *專案*：選擇此選項可在專案層級控制使用者對命名空間資源的存取，然後從清單中選擇一個專案。
+
https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html#netapp-console-organizational-components["深入瞭解"^] 關於 NetApp Console 中的組織元件。



. 選擇 *Register*。




[[related-information]]
== 相關資訊

* link:br-start-discover-kubernetes.html["發現 Kubernetes 工作負載"]
* link:br-rbac-setup.html["在 NetApp Backup and Recovery 中設定基於角色的存取控制"]
* link:reference-roles.html["NetApp Backup and Recovery 角色和權限"]

