---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: 使用 NetApp Backup and Recovery，將內部部署 ONTAP 系統中的 Microsoft SQL Server 應用程式資料保護至 Amazon Web Services、Microsoft Azure 或 StorageGRID。 
---
= 使用 NetApp Backup and Recovery 保護 Microsoft SQL Server 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 NetApp Backup and Recovery，將內部部署 ONTAP 系統中的 Microsoft SQL Server 資料庫備份到 AWS、Azure 或 StorageGRID。實作 3-2-1 備份策略，即在主儲存設備上建立 Snapshot 快照技術、複寫到次要儲存設備，以及複製到物件儲存。

NetApp Backup and Recovery使用NetApp SnapMirror透過建立快照並將其傳輸到備份位置來同步備份。

請使用以下工作流程來保護您的資料：

* link:concept-start-prereq-snapcenter-import.html["如果從SnapCenter匯入，則配置其他項目"]
* link:br-start-discover.html["發現 Microsoft SQL Server 工作負載並選擇性地匯入SnapCenter資源"]
* link:br-use-mssql-backup.html["使用本機ONTAP主儲存上的本機快照備份工作負載"]
* link:br-use-mssql-backup.html["將工作負載複製到ONTAP二級存儲"]
* link:br-use-mssql-backup.html["將工作負載備份到物件儲存位置"]
* link:br-use-mssql-backup.html["立即備份工作負載"]
* link:br-use-mssql-restore.html["恢復工作負載"]
* link:br-use-mssql-clone.html["克隆工作負載"]
* link:br-use-manage-inventory.html["管理工作負載清單"]
* link:br-use-manage-snapshots.html["管理快照"]


若要備份工作負載，您需要建立管理備份和復原作業的策略。看link:br-use-policies-create.html["創建策略"]了解更多。

.支援的備份目標
NetApp Backup and Recovery 支援將下列來源系統中的 Microsoft SQL Server 個體和資料庫備份到公有雲和私有雲中列出的二線系統和物件存放區。Snapshot 快照技術保留在來源系統上。

[cols="33,33,33"]
|===
| 來源系統 | 二線系統（複寫） | 目標物件存放區（備份） 


| AWS 中的Cloud Volumes ONTAP | AWS 本機ONTAP系統中的Cloud Volumes ONTAP | 亞馬遜 S3 ONTAP S3 


| Azure 中的Cloud Volumes ONTAP | Azure 本地端ONTAP系統中的Cloud Volumes ONTAP | Azure Blob ONTAP S3 


| 本地ONTAP系統 | Cloud Volumes ONTAP本地ONTAP系統 | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | 不適用 
|===
.支援的還原目標
您可以將位於主儲存設備、二線系統（複寫 Volume）或物件儲存（備份檔案）中的備份還原至下列目的地系統，以還原 Microsoft SQL Server 個體和資料庫。Snapshot 快照技術位於來源系統上，且只能還原至同一系統。

[cols="33,33,33"]
|===
2+| 從備份檔案位置 | 至目的地系統 


| *物件存放區（備份）* | *二線系統（複寫）* |  


| 亞馬遜 S3 | AWS 本機ONTAP系統中的Cloud Volumes ONTAP | AWS 上的 Cloud Volumes ONTAP 內部部署 ONTAP 系統 ONTAP S3 


| Azure Blob | Azure 本地端ONTAP系統中的Cloud Volumes ONTAP | Azure 中的Cloud Volumes ONTAP本機ONTAP系統ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP本地ONTAP系統 | 本地ONTAP系統ONTAP S3 
|===

NOTE: 「本地ONTAP系統」包括FAS和AFF系統。
