---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp NetApp Backup and Recovery保護您的 VMware 工作負載。 
---
= 使用NetApp Backup and Recovery保護 VMware 工作負載概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用NetApp Backup and Recovery保護您的 VMware VM 和資料儲存。 NetApp Backup and Recovery提供快速、節省空間、崩潰一致和 VM 一致的備份和復原作業。您可以將 VMware 工作負載備份到 Amazon Web Services S3 或StorageGRID ，並將 VMware 工作負載還原至本機 VMware 主機。


NOTE: 此版本的NetApp Backup and Recovery僅支援 VMware vCenter，且無法發現vVols或vVols上的 VM。

使用NetApp Backup and Recovery實作 3-2-1 策略，即在 2 個不同的儲存系統上保留 3 個來源資料副本，並在雲端保留 1 個副本。3-2-1 方法的優點包括：

* 多個資料副本可防止內部和外部網路安全威脅。
* 如果一種媒體發生故障，使用不同類型的媒體可以幫助您恢復。
* 您可以從現場副本快速恢復，如果現場副本受到損害，則可以使用異地副本。



NOTE: 若要切換至NetApp Backup and Recovery UI 版本或從 NetApp Backup and Recovery UI 版本切換，請參閱link:br-start-switch-ui.html["切換到先前的NetApp Backup and RecoveryUI"]。

您可以使用NetApp Backup and Recovery執行與 VMware 工作負載相關的下列任務：

* link:br-use-vmware-discovery.html["發現 VMware 工作負載"]
* link:br-use-vmware-protection-groups.html["為 VMware 工作負載建立和管理保護群組"]
* link:br-use-vmware-backup.html["備份 VMware 工作負載"]
* link:br-use-vmware-restore.html["復原 VMware 工作負載"]

