---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: '您可以從 Windows 用戶作業系統上的虛擬機器磁碟 (VMDK) 還原檔案或資料夾。' 
---
= VMware 訪客檔案還原在 NetApp Backup and Recovery 中的要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用客體檔案還原，可以從 Windows 或 Linux 客體作業系統上的虛擬機器磁碟 （VMDK） 還原檔案或資料夾。



[[guest-file-restore-workflow]]
== 訪客檔案還原工作流程

訪客檔案還原包括下列步驟：

. 附
+
將虛擬磁碟附加到客體 VM 或 Proxy VM，並啟動客體檔案還原工作階段。

. 等待
+
請等待附加操作完成，然後才能瀏覽和恢復。附加操作完成後，會自動建立訪客文件恢復工作階段。

. 選擇檔案或資料夾
+
瀏覽或搜尋虛擬磁碟檔案，然後選擇一個或多個檔案或資料夾進行還原。

. 恢復
+
將選定的檔案或資料夾還原到指定位置。





[[prerequisites-for-restoring-guest-files-and-folders]]
== 恢復訪客文件和資料夾的先決條件

從 VMDK 還原檔案或資料夾之前，請檢閱所有需求。

* VMware ESXi 伺服器上的 443 連接埠（HTTPS）必須開啟才能進行雙向通訊。
* VMware Tools 必須安裝在客體作業系統上並執行。
+
NetApp Backup and Recovery 使用來自 VMware Tools 的資訊來建立與 VMware 客體作業系統的連線。

* 您必須知道要從中還原的備份快照和 VMDK。
* 您附加的虛擬磁碟必須位於 NetApp Backup and Recovery 備份中。
+
包含要還原的檔案或資料夾的虛擬磁碟必須位於使用NetApp Backup and Recovery執行的 VM 備份中。

* 若要使用 Proxy VM，必須先設定 Proxy VM。
+
如果要將虛擬磁碟附加到 proxy VM，則必須在附加和還原作業開始之前設定 proxy VM。

* 對於檔案名稱包含非英文字元的檔案，必須將其還原至目錄中，而非還原為單一檔案。
+
您可以透過恢復檔案所在的目錄來還原包含非英文字元（例如日文漢字）的檔案。



如需客體作業系統支援的最新資訊，請參閱  https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。



[[windows-guests]]
=== Windows 客體

* Windows 客戶作業系統必須執行 Windows Server 2008 R2 或更高版本。
+
有關受支援版本的最新信息，請參閱 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。

* 目標虛擬機器的憑證使用使用者名稱為「Administrator」的內建網域或本機管理員帳號。在開始復原作業之前，請先設定要附加虛擬磁碟的虛擬機器的憑證。附加和恢復操作都需要憑證。工作群組使用者可以使用內建的本機管理員帳戶。
+

IMPORTANT: 如果您必須使用非內建管理員帳戶但在 VM 內具有管理權限的帳戶，則必須在來賓 VM 上停用 UAC。





[[linux-guests]]
=== Linux 客體

* 支援下列客體作業系統發行版本：
+
** 紅帽企業 Linux
** Ubuntu
** Debian


* Run-As 帳戶需要 root 或 sudo 權限。
* 對於跨 VM 還原（還原至不同的 Linux VM），SSH 必須在目標 VM 上執行。




[[guest-file-restore-limitations]]
== 來賓檔案還原限制

從客體作業系統還原檔案或資料夾之前，請審查這些限制。

* 您無法在來賓作業系統內還原動態磁碟類型。
* 如果還原加密的檔案或資料夾，則不會保留加密屬性。
* 您無法將檔案或資料夾還原到加密資料夾。
* 隱藏的文件和資料夾會顯示在文件瀏覽頁面中，但您無法對其進行篩選。
* 您無法在作業系統不同的客體之間還原檔案或資料夾（還原到不同的 VM 時,目的地作業系統類型必須與來源作業系統類型相同）。
* 您無法將 NTFS 檔案系統還原到 FAT 檔案系統。
+
當您嘗試從 NTFS 格式還原為 FAT 格式時，不會複製 NTFS 安全性描述符，因為 FAT 檔案系統不支援 Windows 安全性屬性。

* 您無法從克隆的 VMDK 或未初始化的 VMDK 恢復客戶檔案。
* 您無法復原檔案的目錄結構。
+
從嵌套目錄恢復檔案時，系統只會恢復檔案本身，而不會恢復其目錄結構。若要復原整個目錄樹，請複製頂層目錄。

* 您無法將客戶檔案從 vVol VM 還原到備用主機。
* 您無法恢復加密的訪客檔案。

