---
sidebar: sidebar 
permalink: br-use-kvm-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 您可以保護從本機ONTAP系統到 Amazon Web Services、Microsoft Azure、Google Cloud Platform 和StorageGRID 的KVM 虛擬機，確保您的資料受到保護。 
---
= 保護 KVM 工作負載概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用NetApp Backup and Recovery保護您的託管 KVM 虛擬機器和儲存池。NetApp Backup and Recovery提供快速、節省空間、崩潰一致性和 VM 一致性的備份和復原作業。在使用備份和復原功能保護 KVM 主機和虛擬機器之前，必須先使用 Apache CloudStack 等管理平台來管理它們。

您可以將 KVM 工作負載備份到 Amazon Web Services S3、 Azure NetApp Files或StorageGRID ，並將 KVM 工作負載還原到本機 KVM 主機。

使用NetApp Backup and Recovery實作 3-2-1 保護策略，其中您在 2 個不同的儲存系統上擁有 3 個來源資料副本，並在雲端中擁有 1 個副本。3-2-1 方法的優點包括：

* 多個資料副本可防止內部和外部網路安全威脅。
* 如果一種媒體發生故障，使用不同類型的媒體可以幫助您恢復。
* 您可以從現場副本快速恢復，如果現場副本受到損害，則可以使用異地副本。



NOTE: 若要切換至NetApp Backup and Recovery UI 版本或從 NetApp Backup and Recovery UI 版本切換，請參閱link:br-start-switch-ui.html["切換到先前的NetApp Backup and RecoveryUI"]。

您可以使用NetApp Backup and Recovery執行與 KVM 工作負載相關的下列任務：

* link:br-start-discover-kvm.html["發現 KVM 工作負載"]
* link:br-use-kvm-protection-groups.html["為 KVM 工作負載建立和管理保護群組"]
* link:br-use-kvm-backup.html["備份 KVM 工作負載"]
* link:br-use-kvm-restore.html["恢復 KVM 工作負載"]

