---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery 讓您能夠管理工作負載主機資訊、資料庫資訊和執行個體資訊。您可以查看、編輯和刪除庫存的保護設定。 
---
= 新增和保護 Kubernetes 應用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 讓您輕鬆發現 Kubernetes 集群，而無需生成和上傳 kubeconfig 檔案。您可以使用從NetApp控制台使用者介面複製的簡單命令連接 Kubernetes 叢集並安裝所需的軟體。

.所需的NetApp控制台角色
組織管理員或SnapCenter管理員。link:reference-roles.html["了解NetApp備份與還原存取角色"] 。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp控制台存取角色"^] 。



== 新增並保護新的 Kubernetes 應用程式

保護 Kubernetes 應用程式的第一步是在NetApp Backup and Recovery 中建立應用程式。建立應用程式時，您會讓控制台了解 Kubernetes 叢集上正在執行的應用程式。

.開始之前
在新增和保護 Kubernetes 應用程式之前，您需要link:br-start-discover.html["發現 Kubernetes 工作負載"] 。

.步驟
. 在NetApp Backup and Recovery 中，選擇 *Inventory*。
. 選擇一個 Kubernetes 實例，然後選擇「檢視」以查看與該實例關聯的資源。
. 選擇“*應用程式*”標籤。
. 選擇*建立應用程式*。
. 輸入應用程式的名稱。
. 或者，選擇以下任意欄位來搜尋您想要保護的資源：
+
** 關聯集群
** 關聯的命名空間
** 資源類型
** 標籤選擇器


. （可選）選擇「叢集範圍資源」以選擇任何在叢集層級範圍限定的資源。如果包含這些資源，它們會在建立應用程式時新增到應用程式中。
. 或者，選擇“*搜尋*”以根據您的搜尋條件尋找資源。
+

NOTE: 控制台不會儲存搜尋參數或結果；這些參數用於在選定的 Kubernetes 叢集中搜尋可包含在應用程式中的資源。

. 控制台顯示符合您的搜尋條件的資源清單。
. 如果清單包含您想要保護的資源，請選擇「下一步」。
. （可選）在「*策略*」區域中，選擇現有保護策略來保護應用程序，或建立新策略。如果不選擇策略，則建立的應用程式將不帶保護策略。你可以link:br-use-policies-create.html#create-a-policy["新增保護策略"]之後。
. 在*Prescripts and postscripts*區域中，啟用並配置您想要在備份操作之前或之後執行的任何prescript或postscript執行掛鉤。若要啟用處方或附言，您必須至少已建立了一個link:br-use-manage-execution-hook-templates.html["執行鉤子模板"]。
. 選擇“*創建*”。


.結果
應用程式已建立並出現在 Kubernetes 清單的 *應用程式* 標籤中的應用程式清單中。  NetApp控制台會根據您的設定啟用對應用程式的保護，並且您可以在備份和還原的*監控*區域中監控進度。



== 保護現有的 Kubernetes 應用程式

在已新增的 Kubernetes 應用程式上啟用保護策略。

.步驟
. 在NetApp Backup and Recovery 中，選擇 *Inventory*。
. 選擇一個 Kubernetes 實例，然後選擇「檢視」以查看與該實例關聯的資源。
. 選擇“*應用程式*”標籤。
. 在應用程式清單中，選擇您想要保護的應用程式並選擇相關的操作選單。
. 選擇*保護*。
. 在「*策略*」區域中，選擇現有的保護策略來保護應用程式或建立新策略。參考link:br-use-policies-create.html#create-a-policy["創建策略"]有關建立保護策略的詳細資訊。
. 在*Prescripts and postscripts*區域中，啟用並配置您想要在備份操作之前或之後執行的任何prescript或postscript執行掛鉤。您可以配置執行鉤子的類型、它使用的模板、參數和標籤選擇器。
. 選擇*完成*。


.結果
控制台根據您的設定啟用對應用程式的保護，您可以在備份和還原的*監控*區域中監控進度。一旦您啟用應用程式保護，控制台就會建立該應用程式的完整備份。任何未來的增量備份都將根據您在與該應用程式關聯的保護策略中定義的計劃建立。



== 立即備份 Kubernetes 應用程式

手動建立 Kubernetes 應用程式的備份，為未來的備份和快照建立基線，或確保最新資料受到保護。

.步驟
. 在NetApp Backup and Recovery 中，選擇 *Inventory*。
. 選擇一個 Kubernetes 實例，然後選擇「檢視」以查看與該實例關聯的資源。
. 選擇“*應用程式*”標籤。
. 在應用程式清單中，選擇要備份的應用程式並選擇相關的操作選單。
. 選擇*立即備份*。
. 確保選擇了正確的應用程式名稱。
. 選擇*備份*。


.結果
控制台建立應用程式的備份並在備份和還原的*監控*區域中顯示進度。此備份是根據與應用程式關聯的保護策略建立的。
