---
sidebar: sidebar 
permalink: br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html 
keywords:  
summary: 嘗試還原用戶端檔案時，您可能會遇到用戶端檔案還原工作階段為空白、用戶端檔案還原附加磁碟作業失敗或用戶端檔案還原工作階段停止後備份未分離的情況。 
---
= 在 NetApp Backup and Recovery 中疑難排解 VMware 來賓檔案還原問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果在還原訪客檔案時遇到問題，請使用以下情境來識別並修正問題。



[[guest-file-restore-session-is-blank]]
== 來賓文件恢復會話為空白

如果在建立用戶機檔案復原工作階段期間用戶機作業系統重啟，則會發生此問題。客戶作業系統中的 VMDK 可能處於離線狀態，因此客戶文件復原會話清單為空。

若要解決此問題，請在客戶作業系統中手動將 VMDK 重新置於連線狀態。當 VMDK 線上時，來賓文件恢復工作階段將顯示正確的內容。



[[guest-file-restore-attach-disk-operation-fails]]
== 來賓檔案恢復附加磁碟操作失敗

當您啟動訪客檔案還原作業時，即使 VMware Tools 正在執行且訪客作業系統憑證正確，附加磁碟作業也會失敗，此時會發生此問題。如果發生這種情況，則會傳回下列錯誤：

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMware Tools is running properly on the system and that the account used is an Administrator account. Error is SystemError vix error codes = (3016, 0).`

若要解決此問題，請在客體作業系統上重新啟動 VMware Tools Windows 服務，然後重試客體檔案還原作業。



[[backups-are-not-detached-after-guest-file-restore-session-is-discontinued]]
== 來賓檔案復原會話停止後，備份不會分離

當您從 VM 一致性備份執行來賓檔案還原作業時會發生此問題。當來賓檔案還原工作階段處於活動狀態時，將對相同 VM 執行另一個 VM 一致性備份。當客戶文件恢復會話斷開時（手動或 24 小時後自動斷開），該會話的備份不會被分離。

若要解決此問題，請手動分離從活動來賓檔案還原工作階段附加的 VMDK。
