---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: NetApp Backup and Recovery使您能夠管理執行掛鉤，以便在應用程式保護作業之前或之後採取行動。 
---
= 在 NetApp Backup and Recovery 中管理 Kubernetes 執行掛鉤範本
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
建立執行掛鉤範本，以便在代管 Kubernetes 應用程式的保護作業之前或之後執行自訂指令碼。

[NOTE]
====
NetApp Backup and Recovery 會在資料保護期間，為像 KubeVirt 這樣的應用程式凍結和解除凍結檔案系統。您可以透過 Trident Protect 文件，全域或針對特定應用程式停用此行為：

* 若要為所有應用程式停用此行為，請參閱 https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html#protecting-data-with-kubevirt-vms["使用 KubeVirt 虛擬機器保護數據"]。
* 若要針對特定應用程式停用此行為，請參閱 https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html#define-an-application["定義應用程式"]。


====
*必備的 NetApp Console 角色*

Backup and Recovery 超級管理員、Backup and Recovery 備份管理員或 Backup and Recovery 還原管理員。link:reference-roles.html["了解NetApp Backup and Recovery存取角色"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的NetApp Console存取角色"^].



[[types-of-execution-hooks]]
== 執行鉤子的類型

NetApp Backup and Recovery 根據執行時間支援下列類型的執行掛鉤：

* 預快照
* 快照後
* 預備份
* 備份後
* 恢復後




[[order-of-execution]]
=== 執行順序

執行資料保護作業時，執行掛鉤事件會依照以下順序發生：

. 任何適用的自訂預操作執行掛鉤都在適當的容器上運行。您可以建立多個自訂預操作掛鉤，但它們的執行順序無法保證或配置。
. 如果適用，則會發生檔案系統凍結。
. 執行資料保護操作。
. 如果適用，凍結的檔案系統將被解凍。
. NetApp Backup and Recovery 會在對應的容器上執行所有適用的自訂後操作執行掛鉤。您可以建立多個自訂後操作掛鉤，但其執行順序無法保證或設定。


如果建立多個相同類型的掛勾，其執行順序無法保證。不同類型的掛勾一律依照指定的順序執行。例如，當組態包含所有受支援的掛勾類型時，掛勾將依照以下順序執行：

. 快照前掛鉤執行
. 快照後掛勾執行
. 備份前掛鉤執行
. 備份後掛鉤執行



NOTE: 在生產中啟用執行掛鉤腳本之前對其進行測試。使用“kubectl exec”測試腳本，然後透過將應用程式複製到臨時命名空間並還原來驗證快照和備份。


NOTE: 如果快照前執行鉤子新增、變更或刪除 Kubernetes 資源，則這些變更將包含在快照或備份以及任何後續復原作業中。



[[important-notes-about-custom-execution-hooks]]
== 關於自訂執行鉤子的重要說明

在規劃應用程式的執行掛鉤時，請考慮以下幾點。

* 執行鉤子必須使用腳本來執行操作。許多執行鉤子可以引用同一個腳本。
* 執行掛鉤必須是可執行的 shell 指令碼。
* 腳本大小限制為 96KB。
* 執行掛鉤設定和任何符合條件用於確定哪些掛鉤適用於快照、備份或還原操作。



NOTE: 執行鉤子可能會降低或停用應用程式的功能。請確保自訂鉤子的執行速度盡可能快。如果您取消含有相關執行鉤子的備份或 Snapshot 快照技術操作，且該操作已經開始，則這些鉤子仍會執行。備份後執行鉤子的邏輯不能假定備份已完成。



[[execution-hook-filters]]
== 執行鉤子過濾器

當您新增或編輯應用程式的執行掛鉤時，可以向執行掛鉤新增篩選器，以控制掛鉤匹配哪些 Container。篩選器適用於在所有 Container 上使用相同 Container 映像，但可能將每個映像用於不同用途的應用程式（例如 Elasticsearch）。篩選器可讓您建立執行掛鉤在部分（但不一定全部）相同 Container 上執行的情境。如果為單一執行掛鉤建立多個篩選器，它們將透過邏輯 AND 運算子進行組合。每個執行掛鉤最多可以有 10 個作用中篩選器。

新增至執行鉤子的每個篩選器都使用正規表示式來比對叢集中的 Container。當鉤子比對到 Container 時，它會在該 Container 上執行其關聯的指令碼。篩選器的正規表示式使用正規表示式 2 (RE2) 語法，該語法不支援建立從符合清單中排除 Container 的篩選器。有關 NetApp Backup and Recovery 在執行鉤子篩選器中支援的正規表示式語法的詳細資訊，請參閱 https://github.com/google/re2/wiki/Syntax["正規表示式 2 (RE2) 語法支持"^]。


NOTE: 如果將命名空間過濾器新增至在復原或複製作業後執行的執行掛鉤，且復原或複製來源和目標位於不同的命名空間中，則命名空間篩選器僅適用於目標命名空間。



[[execution-hook-examples]]
== 執行鉤子範例

訪問 https://github.com/NetApp/Verda["NetApp Verda GitHub 項目"]下載流行應用程式（如 Apache Cassandra 和 Elasticsearch）的真實執行掛鉤。您還可以查看範例並獲得建立自己的自訂執行掛鉤的想法。


NOTE: Verda GitHub 程式碼庫中的腳本按原樣提供，不受 NetApp 官方支援。只有 Trident Protect 和 Backup and Recovery 中的執行掛鉤框架才受 NetApp 官方支援。



[[create-an-execution-hook-template]]
== 建立執行鉤子模板

您可以建立自訂執行掛鉤模板，用於在應用程式上執行資料保護操作之前或之後執行操作。


NOTE: 您在此處建立的範本僅可用於保護 Kubernetes 工作負載。

.步驟
. 在控制台中，前往*保護*>*備份和還原*。
. 選擇“*設定*”標籤。
. 展開*執行鉤子模板*部分。
. 選擇*建立執行鉤子模板*。
. 輸入執行掛鉤的名稱。
. （可選）選擇一種鉤子類型。例如，還原後鉤子會在還原作業完成後執行。
. 在 *Script* 文字方塊中，輸入要作為執行掛鉤範本的一部分執行的可執行 shell 腳本。或者，您可以選擇“*上傳腳本*”來上傳腳本檔案。
. 選擇“*創建*”。
+
建立模板後，它將出現在*執行掛鉤模板*部分的模板清單中。


