---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 透過驗證操作環境、控制台代理程式和控制台帳戶的準備情況來開始使用NetApp Backup and Recovery 。要使用NetApp Backup and Recovery，您需要滿足這些先決條件。 
---
= NetApp Backup and Recovery 需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在開始使用 NetApp Backup and Recovery 之前、請確保您的 NetApp Console 和作業環境符合下列要求。



== 準備 NetApp Console

您可以透過 NetApp Console 存取 NetApp Backup and Recovery。若要準備 Console 以進行 Backup and Recovery，您必須：

* 新增 Console 代理程式
* 至少新增一個儲存系統
* 設定 NetApp Console 組織和使用者角色


您需要在 NetApp Console 中擁有 Organization admin 或 Super admin 角色才能完成此準備。

如需進一步了解 NetApp Console，請參閱 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console 統一儲存管理"^]。



=== 完成初始 NetApp Console 設定

如果尚未完成，請完成 NetApp Console 的初始設定。

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["NetApp Console（SaaS 應用程式）入門工作流程"^]



=== 部署 Console 代理程式

Console 代理程式是一個輕量級軟體元件，您可以將其安裝在網路中，以將儲存基礎架構連接到 NetApp Console。它支援進階儲存協調、資料服務和安全的雲端整合。

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解控制台代理"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["部署 Console 代理程式"^]



=== 新增儲存系統

在 Backup and Recovery 中保護工作負載之前，您需要將 ONTAP 儲存系統新增至 Console。

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["在 NetApp Console 中探索內部部署 ONTAP 叢集"^]



=== 設定組織和使用者角色

瞭解組織、專案和使用者角色，然後為使用者配置執行任務所需的適當權限。

請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["將使用者新增至 NetApp Console 組織"]以取得有關使用組織和專案來控制資源存取的資訊。

請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console中的NetApp Backup and Recovery角色"]以瞭解在 NetApp Backup and Recovery 中執行操作所需的角色與權限詳細資訊。



== 物件儲存備份的要求

若要使用物件儲存作為備份目標，您需要擁有 AWS S3、Google Cloud Storage、Microsoft Azure Blob、StorageGRID 或 ONTAP 帳戶，並設定對應的存取權限。



== 保護 ONTAP Volume 工作負載的需求

若要使用 NetApp Backup and Recovery 進行 ONTAP 磁碟區工作負載，您需要滿足下列主機系統、空間和容量大小方面的先決條件。

* 需要 ONTAP 9.8 或更高版本。
* 必須在內部部署 ONTAP 執行個體上啟用 ONTAP One 授權。
* 備份或還原到與 S3 相容的物件儲存需要 ONTAP 9.17.1 或更新版本。


如需支援功能、磁碟區類型、備份與還原目的地等相關資訊，請參閱 link:prev-ontap-protect-overview.html["保護您的ONTAP卷數據"]。



== 保護 Microsoft SQL Server 工作負載的要求

若要將NetApp Backup and Recovery用於 Microsoft SQL Server 工作負載，您需要滿足下列主機系統、空間和大小調整前提條件。

[cols="33,66a"]
|===
| 物品 | 要求 


| 作業系統  a| 
Microsoft Windows 有關受支援版本的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp互通性表工具"^]。



| Microsoft SQL Server 版本  a| 
VMware 虛擬機器檔案系統 (VMFS) 和 VMware 虛擬機器磁碟 (VMDK) NFS 支援 2012 及更高版本。



| SnapCenter伺服器版本  a| 
如果要將現有資料從SnapCenter匯入NetApp Backup and Recovery ，則需要SnapCenter Server 5.0 或更高版本。


NOTE: 如果您已經擁有SnapCenter，請先檢查以確保在從SnapCenter匯入之前已滿足先決條件。看link:concept-start-prereq-snapcenter-import.html["從SnapCenter匯入資源的先決條件"]。



| SQL Server 主機上插件的最小 RAM  a| 
1GB



| SQL Server 主機上插件的最小安裝和日誌空間  a| 
5GB

分配足夠的磁碟空間並監控日誌資料夾的儲存消耗。所需的日誌空間取決於執行的備份次數和資料保護操作的頻率。如果沒有足夠的空間，則不會為操作建立日誌。



| 所需軟體包  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle（以及所有後續的 8.0.x 修補程式）
* PowerShell 7.4.13


有關受支援版本的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp互通性表工具"^]。

|===
[cols="33,66a"]
|===
| 資料庫主機 | 支援的儲存設備 


| 實體伺服器  a| 
* 透過 Fibre Channel 呈現的 LUN
* 透過 iSCSI 呈現的 LUN




| VMware VM  a| 
* iSCSI LUN 透過 iSCSI 啟動器直接連線至客體系統
* 虛擬機器檔案系統 (VMFS)
* NFS 資料存放區




| Hyper-V VM  a| 
iSCSI LUN 透過 iSCSI 啟動器直接連線至客體系統


NOTE: 不支援保護儲存在直通磁碟或 VHD/VHDX 檔案中的資料庫，這些檔案是在 NetApp 儲存設備上配置的。

|===


== 保護 VMware 工作負載的要求

您需要特定的要求來發現和保護您的 VMware 工作負載。

|===
| 要求 | 支援 


| 資料存放區類型 | NFSv3 、 NFSv4.1 和 VMFS 


| VMware ESXi Server 版本 | 7.0U1 及更高版本 


| VMware vCenter vSphere 版本 | 7.0U1 及更高版本 


| VMware Tools | 使用檔案和資料夾還原功能以及 VM 一致性備份時，需要 VMWare Tools。若要確保 VMware Tools 版本與 ESXi Server 版本相符，請參閱 https://packages.vmware.com/tools/versions["VMware 版本對應資訊"]。 


| IP 位址類型 | IPv4、IPv6 


| VMware TLS 版本 | 1.2 、 1.3 


| 連接的儲存設備  a| 
* ONTAP 9.13.1 或更新版本
* 執行 9.13.1 或更新版本的 Amazon FSx for NetApp ONTAP 儲存系統
* ASA r2 SAN 專用系統（需要 ONTAP 9.17.1 或更新版本）


|===
[cols="33,66a"]
|===
| 連接埠類型 | 預配置連接埠 


| VMware ESXi 伺服器連接埠  a| 
443 （HTTPS）、雙向。檔案和資料夾還原功能使用此連接埠。



| 儲存叢集或儲存虛擬機器端口  a| 
* 443 (HTTPS)，雙向。
* 80 （HTTP），雙向。此連接埠用於虛擬應用裝置與儲存 VM 或包含儲存 VM 的叢集之間的通訊。


|===
.保護 VMware 工作負載的角色型存取控制（RBAC）要求
您的 Console 使用者帳戶需要具有 Backup and Recovery 超級管理員角色才能使用 VMware 工作負載。

如需 Backup and Recovery 角色的詳細資訊，請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console 中的備份與還原角色"]。



== 保護 KVM 工作負載的要求

您需要特定的要求來發現和保護 KVM 虛擬機器。

* 運行核心版本 5.14.0-503.22.1.el9_5.x86_64（長期）或更高版本的現代 Linux 發行版
* 您的 KVM 主機和虛擬機器必須由管理平台進行管理。NetApp Backup and Recovery支援以下管理平台：
+
** Apache CloudStack 4.22.0.0


* 確保允許從控制台代理到 KVM 主機的入站網路流量到達連接埠 22。
* QEMU Guest Agent 版本 9.0.0 或更高版本
* libvirt 版本 10.5.0 或更高版本



NOTE: 為確保 KVM 工作負載復原成功完成，請確保在用於 KVM 備份的保護策略中啟用「啟用 VM 一致性快照」設定。

[NOTE]
====
若要啟用對非 root 使用者管理的 KVM 虛擬機器的保護，請依照下列步驟操作：

. 將磁碟區掛載為 NFS3 類型，以避免使用 `nobody` 使用者和群組。
. 使用以下命令將非root使用者新增至 `qemu` 在保留現有群體的同時，組成新的群體：
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. 使用以下命令將掛載路徑的所有權授予… `qemu` 使用者和群組，並更改掛載路徑的權限：
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. 如果存在 NetApp_SnapCenter_Backups 目錄，請將其刪除。


====


== 保護 Oracle 資料庫工作負載的要求

確保您的環境符合發現和保護 Oracle Database 資源的特定要求。

|===
| 要求 | 支援 


| 部署拓撲  a| 
* 獨立式 (NFS、SAN、ASM SAN)
* RAC over ASM（VMDK on VMFS）




| Oracle Database 版本  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| 資料庫儲存 | 必須部署在 NetApp ONTAP （主要或次要）上 


| 主機 OS  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| 物件儲存 （備份目標）  a| 
* Azure 物件儲存
* 亞馬遜 AWS
* NetAppStorageGRID
* ONTAP S3


|===


== 保護 Kubernetes 應用程式的要求

您需要特定的要求來發現 Kubernetes 資源並保護您的 Kubernetes 應用程式。

有關NetApp Console要求，請參閱<<In NetApp Console>>。


NOTE: NetApp 強烈建議為用於 Kubernetes 工作負載的 Console 代理程式指派靜態 IP 位址，以避免在代理程式 IP 位址變更時出現問題。

* 主要 ONTAP 系統（不支援 ASA r2 系統）
* NetApp Trident 25.02 或更高版本
* NetApp Trident Protect 26.05 或更高版本（在 Kubernetes 叢集發現期間安裝）
* Kubernetes 叢集 - 支援的 Kubernetes 發行版和版本包括  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"] 支援的版本。
+
** 確保 Kubernetes 叢集、Trident Protect Connector 和 Trident Protect Proxy 之間的出站方向 TCP 連接埠 443 未被過濾。






== 保護 Hyper-V 工作負載的要求

確保您的 Hyper-V 執行個體符合發現和保護虛擬機器的特定要求。

|===
| 要求 | 支援 


| Microsoft Hyper-V | 2019 、 2022 及 2025 版 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle（以及所有後續的 8.0.x 補丁） 


| PowerShell | 7.4.13 或更新版本 


| 如果非管理員使用者將負責保護 Hyper-V VM ，請確保這些使用者擁有下列權限  a| 
* 本機管理員群組的成員
* 「以服務身分登入」本機安全性原則的一部分




| 請確保在 Windows 防火牆設定中允許下列連接埠的雙向 HTTPS 流量  a| 
* TCP 8144（NetApp Plugin for Hyper-V）
* TCP 8145（NetApp Plugin for Windows）




| 連接的儲存設備  a| 
* ONTAP 9.13.1 或更新版本
* 執行 9.13.1 或更新版本的 Amazon FSx for NetApp ONTAP 儲存系統
* SAN 儲存設備（支援備份以及從主要或次要儲存設備還原到原始位置）


|===
.Hyper-V 主機的硬體需求
* 支援獨立主機和 FCI 叢集主機
* Hyper-V 主機上的NetApp Hyper-V 插件至少需要 1GB RAM
* Hyper-V 主機上插件的最低安裝和日誌空間為 5GB
+

NOTE: 確保在 Hyper-V 主機上為日誌資料夾分配足夠的磁碟空間並定期監控其使用情況。所需空間取決於備份和資料保護操作發生的頻率。如果空間不足，則不會產生日誌。



.NetApp ONTAP 組態需求
* 主ONTAP系統（ONTAP 9.14.1 或更高版本）
* 對於使用 CIFS 共用儲存虛擬機器資料的 Hyper-V 部署，請確保在ONTAP系統上啟用了連續可用性共用屬性。請參閱 https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["ONTAP 文檔"^]以取得說明。

