---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 透過驗證操作環境、控制台代理程式和控制台帳戶的準備情況來開始使用NetApp Backup and Recovery 。要使用NetApp Backup and Recovery，您需要滿足這些先決條件。 
---
= NetApp Backup and Recovery前提條件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
透過驗證操作環境、 NetApp Console代理程式和NetApp Console帳戶的準備情況，開始使用NetApp Backup and Recovery 。要使用NetApp Backup and Recovery，您需要滿足這些先決條件。



== ONTAP 9.8 及更高版本的先決條件

必須在本機ONTAP實例上啟用ONTAP One 授權。



== 備份到物件儲存的先決條件

若要使用物件儲存作為備份目標，您需要一個具有 AWS S3、Microsoft Azure Blob、 StorageGRID或ONTAP 的帳戶並配置適當的存取權限。

* link:prev-ontap-protect-overview.html["保護您的ONTAP卷數據"]




== 保護 Microsoft SQL Server 工作負載的要求

若要將NetApp Backup and Recovery用於 Microsoft SQL Server 工作負載，您需要滿足下列主機系統、空間和大小調整前提條件。

[cols="33,66a"]
|===
| 物品 | 要求 


| 作業系統  a| 
Microsoft Windows 有關受支援版本的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp互通性表工具"^]。



| Microsoft SQL Server 版本  a| 
VMware 虛擬機器檔案系統 (VMFS) 和 VMware 虛擬機器磁碟 (VMDK) NFS 支援 2012 及更高版本。



| SnapCenter伺服器版本  a| 
如果要將現有資料從SnapCenter匯入NetApp Backup and Recovery ，則需要SnapCenter Server 5.0 或更高版本。


NOTE: 如果您已經擁有SnapCenter，請先檢查以確保在從SnapCenter匯入之前已滿足先決條件。看link:concept-start-prereq-snapcenter-import.html["從SnapCenter匯入資源的先決條件"]。



| SQL Server 主機上插件的最小 RAM  a| 
1GB



| SQL Server 主機上插件的最小安裝和日誌空間  a| 
5GB

分配足夠的磁碟空間並監控日誌資料夾的儲存消耗。所需的日誌空間取決於執行的備份次數和資料保護操作的頻率。如果沒有足夠的空間，則不會為操作建立日誌。



| 所需軟體包  a| 
* ASP.NET Core Runtime 8.0.12 託管包（以及所有後續 8.0.x 修補程式）
* PowerShell 7.4.2


有關受支援版本的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp互通性表工具"^]。

|===


== 保護 VMware 工作負載的要求

您需要特定的要求來發現和保護您的 VMware 工作負載。

軟體支援

* 支援 NFS 和 VMFS 資料儲存。不支援vVols 。
* 支援的 NFS 版本：NFS 3 和 NFS 4.1
* 支援的 VMware ESXi Server 版本：7.0U1 以上
* 支援的 VMware vCenter vSphere 版本：7.0U1 及以上
* IP 位址：IPv4 和 IPv6
* VMware TLS：1.2、1.3


*保護 VMware 工作負載的連線和連接埠需求*

[cols="33,66a"]
|===
| 連接埠類型 | 預配置連接埠 


| VMware ESXi 伺服器連接埠  a| 
443（HTTPS），雙向。來賓檔案復原功能使用此連接埠。



| VMware vSphere vCenter Server 連接埠  a| 
如果您正在保護 vVol VM，則必須使用連接埠 443。



| 儲存叢集或儲存虛擬機器端口  a| 
443（HTTPS），雙向。80（HTTP），雙向。此連接埠用於虛擬設備與儲存虛擬機器或包含儲存虛擬機器的叢集之間的通訊。

|===
*保護 VMware 工作負載的基於角色的存取控制 (RBAC) 要求*

vCenter 管理員帳號必須具有所需的 vCenter 權限。

有關所需 vCenter 權限的列表，請參閱 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html#rbac-privileges-required["SnapCenter Plug-in for VMware vSphere vCenter 權限"^]。



== 保護 KVM 工作負載的要求

您需要特定的要求來發現和保護 KVM 虛擬機器。

* 運行核心版本 5.14.0-503.22.1.el9_5.x86_64（長期）或更高版本的現代 Linux 發行版
* 確保允許從控制台代理到 KVM 主機的連接埠 22 的入站流量
* QEMU Guest Agent 版本 9.0.0 或更高版本
* libvirt 版本 10.5.0 或更高版本




== 保護 Oracle 工作負載的要求

確保您的環境符合發現和保護 Oracle 資源的特定要求。

* Oracle 資料庫：
+
** Oracle 19C 和 21C 在獨立部署中支援。
** Oracle 資料庫必須部署在主或輔助NetApp ONTAP儲存中。


* 對象存儲支援：
+
** Azure 物件儲存
** 亞馬遜 AWS
** NetAppStorageGRID
** ONTAP S3






== 保護 Kubernetes 應用程式的要求

您需要特定的要求來發現 Kubernetes 資源並保護您的 Kubernetes 應用程式。

有關NetApp Console要求，請參閱<<在NetApp Console中>>。

* 主ONTAP系統（ONTAP 9.16.1 或更高版本）
* Kubernetes 叢集 - 支援的 Kubernetes 發行版和版本包括：
+
** Anthos On-Prem (VMware) 和 Anthos on Bare Metal 1.16
** Kubernetes 1.27 - 1.33
** OpenShift 4.10 - 4.18
** Rancher Kubernetes Engine 2（RKE2）v1.26.7+rke2r1、v1.28.5+rke2r1
** Suse Rancher


* NetApp Trident 24.10 或更高版本
* NetApp Trident Protect 25.07 或更高版本（在 Kubernetes 工作負載發現期間安裝）
* NetApp Trident Protect Connector 25.07 或更高版本（在 Kubernetes 工作負載發現期間安裝）
+
** 確保 Kubernetes 叢集、 Trident保護連接器和Trident保護代理程式之間的出站方向的 TCP 連接埠 443 未經過濾。






== 保護 Hyper-V 工作負載的要求

確保您的 Hyper-V 執行個體符合發現和保護虛擬機器的特定要求。

* Hyper-V Windows Server 主機的軟體需求：
+
** Microsoft Hyper-V 2019、2022 及 2025 年版本
** ASP.NET Core Runtime 8.0.12 託管包（以及所有後續 8.0.x 修補程式）
** PowerShell 7.4.2 或更高版本
** 確保已安裝主機監護服務角色（請參閱 https://learn.microsoft.com/en-us/windows-server/administration/server-manager/add-remove-roles-features?tabs=gui#add-roles-and-features-to-windows-server["Microsoft Windows Server 文件"^] （取得說明）
** 確保 Windows 防火牆設定中允許下列連接埠進行雙向 HTTPS 通訊：
+
*** 8144（適用於 Hyper-V 的NetApp插件）
*** 8145（適用於 Windows 的NetApp插件）




* Hyper-V 主機的硬體需求：
+
** 支援獨立主機和 FCI 叢集主機
** Hyper-V 主機上的NetApp Hyper-V 插件至少需要 1GB RAM
** Hyper-V 主機上插件的最低安裝和日誌空間為 5GB
+

NOTE: 確保在 Hyper-V 主機上為日誌資料夾分配足夠的磁碟空間並定期監控其使用情況。所需空間取決於備份和資料保護操作發生的頻率。如果空間不足，則不會產生日誌。



* NetApp ONTAP設定需求：
+
** 主ONTAP系統（ONTAP 9.14.1 或更高版本）
** 對於使用 CIFS 共用儲存虛擬機器資料的 Hyper-V 部署，請確保在ONTAP系統上啟用了連續可用性共用屬性。請參閱 https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["ONTAP 文檔"^]以取得說明。






== 在NetApp Console中

確保NetApp Console符合以下要求。

* 控制台使用者應具有對 Microsoft SQL Server 和 Kubernetes 工作負載執行操作所需的角色和權限。要發現資源，您必須具有NetApp Backup and Recovery超級管理員角色。看link:reference-roles.html["NetApp Backup and Recovery基於角色的功能訪問"]有關在NetApp Backup and Recovery中執行操作所需的角色和權限的詳細資訊。
* 具有至少一個活動控制台代理的控制台組織，該代理連接到本地ONTAP叢集或Cloud Volumes ONTAP。
* 至少一個具有NetApp本地ONTAP或Cloud Volumes ONTAP叢集的控制台系統。
* 控制台代理
+
參考 https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["了解如何配置控制台代理"]和 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準NetApp Console要求"^]。

+
** 預覽版需要 Ubuntu 22.04 LTS 作業系統作為控制台代理。






=== 設定NetApp Console

下一步是設定控制台和NetApp Backup and Recovery。

審查 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準NetApp Console要求"^]。



=== 建立控制台代理

您應該聯絡您的NetApp產品團隊來嘗試備份和復原。然後，當您使用控制台代理時，它將包含適合該服務的功能。

若要在使用服務之前在NetApp Console中建立控制台代理，請參閱描述 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何建立控制台代理"^]。

.控制台代理的安裝位置
若要完成還原操作，可以在下列位置安裝控制台代理程式：

ifdef::aws[]

* 對於 Amazon S3，控制台代理可以部署在您的場所。


endif::aws[]

ifdef::azure[]

* 對於 Azure Blob，可以在您的地方部署控制台代理程式。


endif::azure[]

ifdef::gcp[]

endif::gcp[]

* 對於StorageGRID，控制台代理必須部署在您的場所；無論是否有網路存取。
* 對於ONTAP S3，控制台代理可以部署在您的場所（有或沒有網路存取）或雲端供應商環境中



NOTE: 「本地ONTAP系統」包括FAS和AFF系統。
