---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用 NetApp Backup and Recovery 保護您的 VMware 工作負載。 
---
= 使用 NetApp Backup and Recovery 將內部部署 ONTAP 資料備份至與 S3 相容的儲存設備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用此頁面驗證您的組態是否受支援，並設定從您的主要內部部署 ONTAP 系統到 NetApp Backup and Recovery 中的 S3 相容物件儲存設備的備份。



[[verify-support-for-your-configuration]]
== 驗證對您的配置的支持

在開始將磁碟區備份到 S3 相容儲存設備之前、請先閱讀下列需求、確保您擁有支援的組態。

支援的 ONTAP 版本:: ONTAP 最低版本要求為 9.17.1。




[[supported-actions]]
=== 支援的動作

備份到 S3 相容儲存空間時，支援執行以下操作：

* 將內部部署 ONTAP 的當機一致性和應用程式一致性 Snapshot 備份至協力廠商 S3 相容物件儲存區
* 核心資料保護工作流程：備份、還原和備份刪除
* 已使用 Wasabi 物件儲存進行測試和驗證；客戶也報告已成功部署 MinIO 和 IBM Cloud Object Storage
* NetApp Support 接受並分類所有涉及第三方 S3 相容物件儲存的支援要求




[[unsupported-features-and-configurations]]
=== 不支援的功能與組態

備份至 S3 相容儲存設備時，不支援下列功能和組態：

* 不支援自備儲存貯體 (BYOB)
* 備份原則不支援啟用 DataLock
* 備份原則中不支援啟用歸檔模式
* 不支援儲存區層級的加密選項
* 不支援 MetroCluster 組態
* 不支援雲端型 ONTAP 環境，僅支援內部部署的 ONTAP




[[caveats]]
=== 注意事項

將資料備份到 S3 相容儲存設備時、請注意以下幾點：

* * 效能無法保證 *：NetApp 產品對 S3 API 延遲和 IOPS 非常敏感。第三方物件儲存必須提供與 AWS S3 等效的延遲和 IOPS 才能達到類似的效能。NetApp 不提供物件儲存效能故障排除。
* *不承擔資料損壞或遺失的責任*：NetApp 對於因第三方 S3 物件儲存問題而導致的資料遺失或服務中斷概不負責。
* *功能支援有限*：第三方 S3 相容目標的支援功能集是原生目標（AWS S3、Azure Blob、GCP、ONTAP S3、StorageGRID）可用功能集的子集。




[[prepare-your-console-agent]]
== 準備控制台代理

控制台代理程式是NetApp Console功能的主要軟體。需要控制台代理程式來備份和還原您的ONTAP資料。



[[create-or-switch-console-agents]]
=== 建立或切換控制台代理

將資料備份到 S3 相容儲存設備時，您的本機或雲端必須部署有 Console 代理程式。您需要安裝新的 Console 代理程式，或確保目前選取的 Console 代理程式位於上述位置之一。內部部署的 Console 代理程式可安裝在有或沒有網際網路存取的站台中。

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["了解控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["在您的雲端環境中安裝控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["在具有網際網路存取權限的 Linux 主機上安裝控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["在沒有網際網路存取的 Linux 主機上安裝控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["在控制台代理之間切換"^]




[[prepare-console-agent-networking-requirements]]
=== 準備控制台代理網路要求

確保安裝控制台代理程式的網路啟用以下連線：

* 透過連接埠 443 與 S3 相容伺服器建立 HTTPS 連線
* 透過連接埠 443 建立到來源ONTAP叢集管理 LIF 的 HTTPS 連接
* 透過連接埠 443 到NetApp Backup and Recovery 的出站網路連線（當控制台代理安裝在「暗站」時不需要）




==== 私人模式（暗站）注意事項

NetApp Backup and Recovery功能內建於控制台代理程式中。以私人模式安裝時，您需要定期更新控制台代理軟體才能存取新功能。檢查link:whats-new.html["NetApp Backup and Recovery新功能"]查看每個NetApp Backup and Recovery版本中的新功能。當您想要使用新功能時，請按照以下步驟操作 https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["升級控制台代理軟體"^]。

當您在標準 SaaS 環境中使用 NetApp 備份與還原時，NetApp 備份與還原組態資料會備份到雲端。當您在無法存取網際網路的站台中使用 NetApp 備份與還原時，NetApp 備份與還原組態資料會備份到儲存備份的 S3 相容儲存桶。



[[verify-license-requirements]]
== 驗證許可證要求

在為叢集啟動NetApp Backup and Recovery之前，您需要從NetApp購買並啟動NetApp Backup and Recovery BYOL 授權。此授權用於備份和還原物件儲存 - 建立快照或複製磁碟區不需要授權。此許可證適用於該帳戶，可跨多個系統使用。

您需要NetApp提供的序號，以便您在許可證的有效期限和容量內使用本服務。link:br-start-licensing.html["了解如何管理您的 BYOL 許可證"]。


TIP: 將檔案備份到 S3 相容儲存設備時，不支援 PAYGO 授權。



[[prepare-your-ontap-clusters]]
== 準備ONTAP集群

準備來源本機ONTAP系統和任何輔助本機ONTAP或Cloud Volumes ONTAP系統。

準備ONTAP集群涉及以下步驟：

* 在NetApp Console中發現您的ONTAP系統
* 驗證ONTAP系統要求
* 驗證ONTAP網路要求以將資料備份到對象存儲
* 驗證ONTAP複製卷的網路要求




[[discover-your-ontap-systems-in-netapp-console]]
=== 在NetApp Console中發現您的ONTAP系統

您的來源本機ONTAP系統和任何輔助本機ONTAP或Cloud Volumes ONTAP系統都必須在NetApp Console*系統* 頁面上可用。

您需要知道叢集管理 IP 位址和管理員使用者帳戶的密碼才能新增叢集。https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["了解如何發現集群"^]。



[[verify-ontap-system-requirements]]
=== 驗證ONTAP系統要求

確保您的ONTAP系統符合以下要求：

* 最低版本為ONTAP 9.8；建議使用ONTAP 9.8P13 及更高版本。
* SnapMirror許可證（包含在高級捆綁包或資料保護捆綁包中）。
+
*注意：*使用NetApp Backup and Recovery時不需要「混合雲端捆綁包」。

+
了解如何 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理您的叢集許可證"^]。

* 時間和時區設定正確。了解如何 https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["配置叢集時間"^]。
* 如果您複製數據，請檢查來源系統和目標系統是否要執行相容的ONTAP版本。
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["查看與SnapMirror關係相容的ONTAP版本"^]。





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== 驗證ONTAP網路要求以將資料備份到對象存儲

您必須確保連接到物件儲存的系統符合以下要求。

[NOTE]
====
* 當您使用扇出備份架構時，必須在主儲存系統上設定設定。
* 當您使用級聯備份架構時，必須在_輔助_儲存系統上設定設定。
+
link:prev-ontap-protect-journey.html["了解有關備份架構類型的更多信息"]。



====
需滿足以下ONTAP集群網路需求：

* ONTAP 叢集透過使用者指定的連接埠，從叢集間 LIF 發起與 S3 相容伺服器的 HTTPS 連線，以進行備份與恢復作業。此連接埠可在備份設定期間進行設定。
+
ONTAP從物件儲存讀取和寫入資料。物件儲存從不啟動，它只是響應。

* ONTAP需要從控制台代理到叢集管理 LIF 的入站連線。
* 每個託管要備份的磁碟區的ONTAP節點上都需要一個叢集間 LIF。  LIF 必須與ONTAP用於連接物件儲存的 _IPspace_ 相關聯。 https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["了解有關 IP 空間的更多信息"^] 。
+
當您設定NetApp Backup and Recovery時，系統會提示您輸入要使用的 IP 空間。您應該選擇與每個 LIF 關聯的 IP 空間。這可能是「預設」 IP 空間或您建立的自訂 IP 空間。

* 節點的群集間 LIF 能夠存取物件儲存（當控制台代理安裝在「暗」站點時不需要）。
* 已為磁碟區所在的儲存虛擬機器設定 DNS 伺服器。了解如何 https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["為 SVM 配置 DNS 服務"^]。
* 如果您使用的 IPspace 與 Default 不同，則可能需要建立靜態路由才能存取物件儲存設備。
* 如有必要，請更新防火牆規則，以允許NetApp Backup and Recovery服務透過您指定的連接埠（通常為連接埠 443）從ONTAP連接到物件存儲，並透過連接埠 53（TCP/UDP）從儲存虛擬機器到 DNS 伺服器的名稱解析流量。




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== 驗證ONTAP複製卷的網路要求

如果您打算使用NetApp Backup and Recovery在輔助ONTAP系統上建立複製卷，請確保來源系統和目標系統符合下列網路需求。

* 如果叢集位於本機，則您應該從公司網路連接到雲端提供者中的虛擬網路。這通常是 VPN 連線。
* ONTAP叢集必須滿足額外的子網路、連接埠、防火牆和叢集要求。




[[activate-backups-on-your-ontap-volumes]]
== 啟動ONTAP磁碟區上的備份

隨時直接從您的本機系統啟動備份。

嚮導將引導您完成以下主要步驟：

* 選擇要備份的捲
* 定義備份策略和政策
* 檢查您的選擇


您還可以<<顯示 API 命令>>在審查步驟中，您可以複製程式碼來自動為未來的系統啟動備份。



[[start-the-wizard]]
=== 啟動精靈

.步驟
. 您可以透過以下方式之一存取「啟動備份與恢復」精靈：
+
** 在 Console 的 *Systems* 頁面中，選擇系統，然後在右側面板的 Backup and Recovery 旁邊選擇 *Enable > Backup Volumes*。
** 在備份和復原欄中選擇*卷*。從「磁碟區」標籤中，選擇「操作 (...)」選項，然後為單一磁碟區（尚未啟用複製或備份到物件儲存）選擇「啟動備份」。


+
精靈的簡介頁面顯示了保護選項，包括本機快照、複製和備份。如果您在此步驟中選擇了第二個選項，則會出現「定義備份策略」頁面，其中選擇一個磁碟區。

. 繼續以下選項：
+
** 如果您已經有控制台代理，那麼一切就緒了。只需選擇*下一步*。
** 如果您沒有控制台代理，則會出現「新增控制台代理」選項。參考<<準備控制台代理>>。






[[select-the-volumes-that-you-want-to-back-up]]
=== 選擇要備份的捲

選擇您想要保護的磁碟區。受保護的磁碟區是具有以下一項或多項的磁碟區：快照策略、複製策略、備份到物件策略。

您可以選擇保護FlexVol或FlexGroup磁碟區；但是，在啟動系統備份時不能選擇這些磁碟區的混合。了解如何link:prev-ontap-backup-manage.html["啟動系統中附加磁碟區的備份"]（FlexVol或FlexGroup）在為初始磁碟區配置備份後。

[NOTE]
====
* 您一次只能在單一FlexGroup磁碟區上啟動備份。
* 選擇要保護的來源磁碟區時，只能選擇具有相符 SnapLock 設定的磁碟區。所選磁碟區必須全部啟用 SnapLock 功能，或全部停用 SnapLock 功能。


====
.步驟
請注意，如果您選擇的磁碟區已經套用了快照或複製策略，那麼您稍後選擇的策略將覆寫這些現有策略。

. 在「選擇卷」頁面中，選擇要保護的一個或多個磁碟區。
+
** 或者，過濾行以僅顯示具有特定卷類型、樣式等的捲，以便更輕鬆地進行選擇。
** 選擇第一個磁碟區後，您可以選擇所有FlexVol磁碟區（FlexGroup磁碟區一次只能選擇一個）。若要備份所有現有的FlexVol卷，請先選取一個卷，然後選取標題行中的框。
** 若要備份單一卷，請選取每個卷對應的複選框。


. 選擇“下一步”。




[[define-the-backup-strategy]]
=== 定義備份策略

定義備份策略涉及配置以下選項：

* 保護選項：您是否要實施一個或所有備份選項：本機快照、複製和備份到物件存儲
* 架構：您是否要使用扇出式或級聯備份架構
* 本機快照策略
* 複製目標和策略
* 備份到物件儲存資訊（提供者、加密、網路、備份策略和匯出選項）。


.步驟
. 在「定義備份策略」頁面中，選擇以下一項或全部。預設情況下，所有三個都被選中：
+
** *本機快照*：建立本機快照。
** *複製*：在另一個ONTAP儲存系統上建立複製磁碟區。
** *備份*：將磁碟區備份到為 S3 設定的ONTAP系統上的儲存桶。


. *架構*：如果您同時選擇了複製和備份，請選擇下列資訊流之一：
+
** *級聯*：備份資料從主系統流向輔助系統，然後從輔助系統流向物件儲存。
** *扇出*：備份資料從主系統流向輔助系統，並從主系統流向物件儲存。
+
有關這些架構的詳細信息，請參閱link:prev-ontap-protect-journey.html["規劃您的保育之旅"]。



. *本機快照*：選擇現有的快照原則或建立新的快照策略。
+

TIP: 如果您想要在啟動快照之前建立自訂策略，則可以使用 System Manager 或ONTAP CLI `snapmirror policy create`命令。參考。

+

TIP: 若要使用備份和復原建立自訂策略，請參閱link:br-use-policies-create.html["創建策略"]。

+
若要建立策略，請選擇「建立新策略」並執行下列操作：

+
** 輸入策略的名稱。
** 選擇最多五個時間表，通常頻率不同。
** 選擇“*創建*”。


. *複製*：如果選擇了*複製*，請設定以下選項：
+
** *複寫目標*：選擇目的地系統和儲存 VM。您也可以選擇目的地 Aggregate（或 FlexGroup Volume 的多個 Aggregate），以及將新增至複寫 Volume 名稱的前置詞或後置詞。
** *複製策略*：選擇現有的複製策略或建立新的複製策略。
+
若要建立策略，請選擇「建立新策略」並執行下列操作：

+
*** 輸入策略的名稱。
*** 選擇最多五個時間表，通常頻率不同。
*** 選擇“*創建*”。




. *備份到物件*：如果您選擇了*備份*，請設定以下選項：
+
** *提供者*：選擇* ONTAP S3*。
** *提供者設定*：輸入 S3 伺服器 FQDN 詳細資料、連接埠以及使用者的存取金鑰和金鑰。
+
存取金鑰和金鑰用於您建立的用戶，以授予ONTAP叢集對 S3 儲存桶的存取權限。

** *網路*：選擇要備份的磁碟區所在的來源ONTAP叢集中的 IP 空間。此 IP 空間的群集間 LIF 必須具有出站網際網路存取權限（當控制台代理安裝在「暗站」時不需要）。
+

TIP: 選擇正確的 IP 空間可確保NetApp Backup and Recovery可以建立從ONTAP到ONTAP S3 物件儲存的連線。

** *備份策略*：選擇現有的備份策略或建立新的備份策略。
+

TIP: 您可以使用 System Manager 或ONTAP CLI 建立政策。使用ONTAP CLI 建立自訂策略 `snapmirror policy create`命令，請參閱。

+

TIP: 若要使用備份和復原建立自訂策略，請參閱link:br-use-policies-create.html["創建策略"]。

+
若要建立策略，請選擇「建立新策略」並執行下列操作：

+
*** 輸入策略的名稱。
*** 選擇最多五個時間表，通常頻率不同。
*** 對於備份至物件原則，請設定 DataLock 和勒索軟體保護設定。如需 DataLock 和勒索軟體保護的詳細資訊，請參閱 link:prev-ontap-policy-object-options.html["備份到對象策略設置"]。
*** 選擇“*創建*”。


** *將現有快照匯出至物件儲存作為備份檔案*：如果此系統中存在與您剛剛選擇的備份計畫標籤（例如，每日、每週等）相符的磁碟區的本機快照，則會顯示此附加提示。選取此方塊可將所有歷史快照複製到物件儲存作為備份文件，以確保對您的磁碟區進行最全面的保護。


. 選擇“下一步”。




[[review-your-selections]]
=== 檢查您的選擇

這是審查您的選擇並在必要時進行調整的機會。

.步驟
. 在「審核」頁面中，審核您的選擇。
. （可選）選取核取方塊*自動將快照原則標籤與複製和備份策略標籤同步*。這將建立具有與複製和備份策略中的標籤相符的標籤的快照。如果策略不匹配，則不會建立備份。
. 選擇*啟動備份*。


.結果
NetApp Backup and Recovery開始對您的磁碟區進行初始備份。複製捲和備份檔案的基線傳輸包括來源資料的完整副本。後續傳輸包含快照中包含的主儲存資料的差異副本。

在目標叢集中建立一個複製卷，該卷將與主儲存卷同步。

在您輸入的 S3 存取金鑰和金鑰指示的服務帳戶中建立一個 S3 儲存桶，並將備份檔案儲存在那裡。

顯示磁碟區備份儀表板，以便您可以監控備份的狀態。

您也可以使用link:br-use-monitor-tasks.html["作業監控頁面"]。



[[show-the-api-commands]]
=== 顯示 API 命令

您可能需要顯示並（可選）複製「啟動備份與還原」精靈中使用的 API 命令。您可能需要執行此操作，以便在未來的系統中自動化備份啟動。

.步驟
. 在「啟動備份與還原」精靈中，選取 *View API request*。
. 若要將指令複製到剪貼簿，請選擇*複製*圖示。

