---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp NetApp Backup and Recovery保護您的 VMware 工作負載。 
---
= SnapCenter Plug-in for VMware vSphere以與NetApp Backup and Recovery一起使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該在NetApp Backup and Recovery中註冊SnapCenter Plug-in for VMware vSphere，以便顯示資料儲存區和虛擬機器。只有具有管理權限的使用者才能註冊SnapCenter Plug-in for VMware vSphere。


NOTE: 若要切換至NetApp Backup and Recovery工作負載，請參閱link:br-start-switch-ui.html["切換到不同的NetApp Backup and Recovery工作負載"]。

.步驟
. 在NetApp ConsoleUI 中，選擇 *保護* > *備份與還原* > *虛擬機器*。
. 從「*設定*」下拉式選單中，選擇「SnapCenter Plug-in for VMware vSphere*」。
. 選擇*SnapCenter Plug-in for VMware vSphere*。
. 指定以下詳細資訊：
+
.. 在SnapCenter Plug-in for VMware vSphere中，指定SnapCenter Plug-in for VMware vSphere的 FQDN 或 IP 位址。
.. 在連接埠欄位中，指定執行SnapCenter Plug-in for VMware vSphere埠號碼。
+
您應該確保在預設 8144 連接埠上執行的SnapCenter Plug-in for VMware vSphere與可在任何雲端提供者（Amazon Web Services、Microsoft Azure、Google Cloud Platform）或本機執行的控制台代理程式執行個體之間的通訊暢通。

.. 在使用者名稱和密碼欄位中，指定具有管理員角色的 vCenter 使用者的憑證。


. 選擇*註冊*。


*完成後*

選擇「*備份和復原*」>「*虛擬機器*」以查看使用已註冊的SnapCenter Plug-in for VMware vSphere保護的所有資料儲存和虛擬機器。
