---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp NetApp Backup and Recovery保護您的 VMware 工作負載。 
---
= 在NetApp Backup and Recovery中保護虛擬機器工作負載概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用NetApp Backup and Recovery保護您的虛擬機器工作負載。  NetApp Backup and Recovery和 VMDK 提供快速、節省空間、崩潰一致和虛擬機器一致的備份和還原作業。

您可以將資料儲存備份至 Amazon Web Services S3、Microsoft Azure Blob、Google Cloud Platform 和StorageGRID ，並將虛擬機器還原回SnapCenter Plug-in for VMware vSphere。

[]
====
*注意* 若要切換至NetApp Backup and Recovery工作負載，請參閱link:br-start-switch-ui.html["切換到不同的NetApp Backup and Recovery工作負載"]。

====
有關保護虛擬機器工作負載的說明，請參閱以下主題：

* link:prev-vmware-policy-create.html["為 VMware 工作負載建立策略"]
* link:prev-vmware-backup-aws.html["將 VMware 資料儲存備份到 Amazon Web Services"]
* link:prev-vmware-backup-azure.html["將 VMware 資料儲存體備份到 Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["將 VMware 資料儲存區備份到 Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["將 VMware 資料儲存備份到StorageGRID"]
* link:prev-vmware-restore.html["復原 VMware 工作負載"]
* link:prev-vmware-manage.html["管理 VMware 工作負載的保護"]

