---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery 支援一個 Google 歸檔儲存類別和大多數區域。 
---
= NetApp備份與復原支援 Google 歸檔儲存層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 支援一個 Google 歸檔儲存類別和大多數區域。

[]
====
*注意* 若要切換到NetApp Backup and Recovery UI 版本，請參閱link:br-start-switch-ui.html["切換到先前的NetApp備份與還原 UI"]。

====


== NetApp備份和還原支援的 Google 歸檔儲存類

最初建立備份檔案時，它們儲存在_標準_儲存中。此層針對儲存不經常存取的資料進行了最佳化；但也允許您立即存取它。

如果您的本地叢集使用的是ONTAP 9.12.1 或更高版本，您可以選擇在一定天數（通常超過 30 天）後將舊備份分層到NetApp備份和還原 UI 中的「_Archive_」儲存中，以進一步最佳化成本。此層中的資料將需要更高的檢索成本，因此您需要考慮可能需要多久從這些存檔的備份檔案中還原資料。請參閱此頁面上有關從檔案儲存復原資料的部分。

請注意，當您使用此類生命週期規則配置NetApp Backup and Recovery 時，在 Google 帳戶中設定儲存桶時不得配置任何生命週期規則。

https://cloud.google.com/storage/docs/storage-classes["了解 Google 儲存類別"^] 。



== 從檔案儲存中復原數據

雖然將較舊的備份檔案儲存在存檔儲存中比標準儲存便宜得多，但從存檔儲存中的備份檔案中存取資料進行復原作業將花費更長的時間並且花費更多。

從 Google Archive 恢復資料需要多少錢？:: 若要了解按地區劃分的 Google Cloud Storage 詳細定價，請造訪 https://cloud.google.com/storage/pricing["Google Cloud Storage 定價頁面"^]。
要恢復我在 Google Archive 中存檔的物件需要多長時間？:: 總還原時間由兩部分組成：
+
--
* *檢索時間*：從存檔中檢索備份檔案並將其放置在標準儲存中的時間。這有時被稱為“補水”時間。與其他雲端供應商提供的「最冷」儲存解決方案不同，您的資料可以在幾毫秒內存取。
* *恢復時間*：從標準儲存中的備份檔案還原資料的時間。這次與不使用存檔層時直接從標準儲存進行的典型復原作業沒有什麼不同。


--

