---
sidebar: sidebar 
permalink: prev-reference-aws-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery 支援兩種 S3 存檔儲存類別和大多數區域。 
---
= NetApp備份和復原支援的 AWS 存檔儲存層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 支援兩種 S3 存檔儲存類別和大多數區域。

[]
====
*注意* 若要切換到NetApp Backup and Recovery UI 版本，請參閱link:br-start-switch-ui.html["切換到先前的NetApp備份與還原 UI"]。

====


== NetApp備份與復原支援的 S3 歸檔儲存類

最初建立備份檔案時，它們會儲存在 S3 _Standard_ 儲存中。此層針對儲存不經常存取的資料進行了最佳化；但也允許您立即存取它。  30 天后，備份將轉換為 S3_標準-不頻繁存取_儲存類別以節省成本。

如果您的來源叢集運行的是ONTAP 9.10.1 或更高版本，您可以選擇在一定天數（通常超過 30 天）後將備份分層到 _S3 Glacier_ 或 _S3 Glacier Deep Archive_ 存儲，以進一步優化成本。您可以將其設定為“0”或 1-999 天。如果將其設為“0”天，則以後不能將其變更為1-999天。

這些層中的資料在需要時無法立即訪問，並且需要更高的檢索成本，因此您需要考慮可能需要多久從這些存檔的備份檔案中恢復資料。請參閱此頁面上有關從檔案儲存復原資料的部分。

* 如果您在啟動NetApp Backup and Recovery 時在第一個備份策略中未選擇任何存檔層，那麼 _S3 Glacier_ 將是您未來策略的唯一存檔選項。
* 如果您在第一個備份策略中選擇了“S3 Glacier”，那麼您可以將該叢集的未來備份策略變更為“S3 Glacier Deep Archive”層。
* 如果您在第一個備份策略中選擇“S3 Glacier Deep Archive”，則該層將是該叢集未來備份策略唯一可用的存檔層。


請注意，當您使用此類生命週期規則配置NetApp Backup and Recovery 時，在 AWS 帳戶中設定儲存桶時不得配置任何生命週期規則。

https://aws.amazon.com/s3/storage-classes/["了解 S3 儲存類別"^] 。



== 從檔案儲存中復原數據

雖然將較舊的備份檔案儲存在檔案儲存中比標準或標準 IA 儲存便宜得多，但從檔案儲存中的備份檔案中存取資料以進行復原作業將花費更長的時間並且花費更多。

從 Amazon S3 Glacier 和 Amazon S3 Glacier Deep Archive 恢復資料需要多少費用？:: 從 Amazon S3 Glacier 擷取資料時，您可以選擇 3 個還原優先權；從 Amazon S3 Glacier Deep Archive 擷取資料時，您可以選擇 2 個還原優先權。  S3 Glacier Deep Archive 的成本低於 S3 Glacier：
+
--
[cols="25,25,25,25"]
|===
| 存檔層 3+| 恢復優先順序和成本 


|  | *高的* | *標準* | *低的* 


| *S3 冰河* | 檢索速度最快，成本最高 | 檢索速度較慢，成本較低 | 檢索速度最慢，成本最低 


| *S3 Glacier 深度存檔* |  | 檢索速度更快，成本更高 | 檢索速度較慢，成本最低 
|===
每種方法都有不同的每 GB 檢索費用和每個請求費用。有關 AWS 區域 S3 Glacier 的詳細定價，請造訪 https://aws.amazon.com/s3/pricing/["Amazon S3 定價頁面"^]。

--
恢復存檔在 Amazon S3 Glacier 中的物件需要多長時間？:: 總還原時間由兩部分組成：
+
--
* *檢索時間*：從存檔中檢索備份檔案並將其放置在標準儲存中的時間。這有時被稱為“補水”時間。檢索時間根據您選擇的復原優先順序而不同。
+
[cols="25,20,20,20"]
|===
| 存檔層 3+| 復原優先權和檢索時間 


|  | *高的* | *標準* | *低的* 


| *S3 冰河* | 3-5分鐘 | 3-5小時 | 5-12小時 


| *S3 Glacier 深度存檔* |  | 12小時 | 48小時 
|===
* *恢復時間*：從標準儲存中的備份檔案還原資料的時間。這次與不使用存檔層時直接從標準儲存進行的典型復原作業沒有什麼不同。


有關 Amazon S3 Glacier 和 S3 Glacier Deep Archive 檢索選項的更多信息，請參閱 https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["關於這些儲存類別的 Amazon 常見問題解答"^]。

--

