---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, Console agent 
summary: 在沒有網際網路存取的網站（稱為「私有模式」）中使用NetApp Backup and Recovery時， NetApp Backup and Recovery設定資料將備份到儲存備份的StorageGRID或ONTAP S3 儲存桶中。如果您將來遇到控制台代理主機系統問題，您可以部署新的控制台代理並還原關鍵的NetApp Backup and Recovery資料。 
---
= 在暗站中恢復NetApp Backup and Recovery配置數據
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在沒有網際網路存取的網站（稱為_私有模式_）中使用NetApp Backup and Recovery時， NetApp Backup and Recovery設定資料將備份到儲存備份的StorageGRID或ONTAP S3 儲存桶中。如果控制台代理主機系統出現問題，您可以部署新的控制台代理並還原關鍵的NetApp Backup and Recovery資料。


NOTE: 此過程僅適用於ONTAP磁碟區資料。

當您在 SaaS 環境中使用NetApp Backup and Recovery時，其中控制台代理部署在雲端供應商處，或在您自己的具有網際網路存取權限的主機系統上，所有重要的NetApp Backup and Recovery設定資料都會在雲端中備份和保護。如果您遇到控制台代理問題，只需建立新的控制台代理並新增您的系統，備份詳細資訊就會自動還原。

備份的資料有兩種類型：

* NetApp Backup and Recovery資料庫 - 包含所有磁碟區、備份檔案、備份策略和設定資訊的清單。
* 索引目錄檔案 - 包含用於搜尋和復原功能的詳細索引，可讓您在尋找要復原的磁碟區資料時搜尋非常快速且有效。


這些資料每天午夜備份一次，每個檔案最多保留 7 份副本。如果控制台代理程式正在管理多個本機ONTAP系統，則NetApp Backup and Recovery檔案將位於首先啟動的系統的儲存桶中。


TIP: NetApp Backup and Recovery資料庫或索引目錄檔案中從未包含任何磁碟區資料。



== 將NetApp Backup and Recovery資料還原到新的控制台代理

如果您的內部控制台代理發生災難性故障，您將需要安裝新的控制台代理，然後將NetApp Backup and Recovery資料還原到新的控制台代理。

您需要執行下列任務才能讓NetApp Backup and Recovery系統還原工作狀態：

* 安裝新的控制台代理
* 還原NetApp Backup and Recovery資料庫
* 恢復索引目錄文件
* 將所有本機ONTAP系統和StorageGRID系統重新發現到NetApp ConsoleUI


一旦您確認系統恢復正常運作，我們建議您建立新的備份檔案。

.你需要什麼
您需要從儲存備份檔案的StorageGRID或ONTAP S3 儲存桶存取最新的資料庫和索引備份：

* NetApp Backup and RecoveryMySQL 資料庫文件
+
該檔案位於儲存桶中的以下位置 `netapp-backup-<GUID>/mysql_backup/`，它被命名為 `CBS_DB_Backup_<day>_<month>_<year>.sql`。

* 索引目錄備份 zip 文件
+
該檔案位於儲存桶中的以下位置 `netapp-backup-<GUID>/catalog_backup/`，它被命名為 `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`。





=== 在新的本機 Linux 主機上安裝新的控制台代理

安裝新的控制台代理程式時，請確保下載與原始控制台代理程式上安裝的相同版本的軟體。 NetApp Backup and Recovery資料庫結構的定期變更可能會導致較新的軟體版本與原始資料庫備份不相容。你可以 https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["恢復備份資料庫後，將控制台代理軟體升級至最新版本"^]。

. https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["在新的本機 Linux 主機上安裝控制台代理"^]
. 使用您剛剛建立的管理員使用者憑證登入控制台。




=== 還原NetApp Backup and Recovery資料庫

. 將 MySQL 備份從備份位置複製到新的控制台代理主機。下面我們將使用範例檔案名稱「CBS_DB_Backup_23_05_2023.sql」。
. 根據您使用的是 Docker 還是 Podman 容器，使用以下命令之一將備份複製到 MySQL docker 容器：
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. 根據您使用的是 Docker 還是 Podman 容器，使用以下命令之一進入 MySQL 容器 shell：
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. 在容器shell中，部署「env」。
. 您將需要 MySQL DB 密碼，因此請複製鍵“MYSQL_ROOT_PASSWORD”的值。
. 使用下列命令還原NetApp Backup and RecoveryMySQL DB：
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. 使用下列 SQL 指令驗證NetApp Backup and Recovery MySQL DB 是否已正確還原：
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
輸入密碼。

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
檢查顯示的捲是否與原始環境中存在的捲相同。





=== 恢復索引目錄文件

. 將 Indexed Catalog 備份 zip 檔案（我們將使用範例檔案名稱「Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip」）從備份位置複製到「/opt/application/netapp/cbs」資料夾中的新控制台代理主機。
. 使用下列命令解壓縮「Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip」檔案：
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. 執行 *ls* 命令以確保已建立資料夾“catalogdb1”，其下有子資料夾“changes”和“snapshots”。




=== 發現您的ONTAP叢集和StorageGRID系統

. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["探索所有本地ONTAP系統"^]在您之前的環境中可用。這包括您用作 S3 伺服器的ONTAP系統。
. https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["發現您的StorageGRID系統"^]。




=== 設定StorageGRID環境詳細信息

添加與您的ONTAP系統關聯的StorageGRID系統的詳細信息，因為它們是在原始控制台代理設定上使用 https://docs.netapp.com/us-en/console-automation/index.html["NetApp ConsoleAPI"^]。

以下資訊適用於從NetApp Console 3.9.xx 開始的私有模式安裝。對於舊版本，請使用以下步驟： https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite 雲端備份：MySQL 和索引目錄備份和還原"^] 。

您需要對將資料備份到StorageGRID 的每個系統執行這些步驟。

. 使用以下 oauth/token API 提取授權令牌。
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
雖然 IP 位址、使用者名稱和密碼是自訂值，但帳戶名稱不是。帳戶名稱始終為“account-DARKSITE1”。此外，使用者名稱必須使用電子郵件格式的名稱。

+
此 API 將傳回以下回應。您可以如下所示檢索授權令牌。

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. 使用 tenancy/external/resource API 提取系統 ID 和 X-Agent-Id。
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
此 API 將傳回以下回應。「resourceIdentifier」下的值表示_WorkingEnvironment Id_，「agentId」下的值表示_x-agent-id_。

. 使用與系統關聯的StorageGRID系統的詳細資訊更新NetApp Backup and Recovery資料庫。確保輸入StorageGRID的完全限定網域名稱以及存取金鑰和儲存金鑰，如下所示：
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== 驗證NetApp Backup and Recovery設置

. 選擇每個ONTAP系統，然後點擊右側面板中備份和還原服務旁邊的「檢視備份」。
+
您應該能夠看到為您的捲創建的所有備份。

. 在「恢復儀表板」的「搜尋與復原」部分下，按一下「*索引設定*」。
+
確保先前啟用了索引編目的系統仍然保持啟用狀態。

. 在「搜尋和復原」頁面中，執行一些目錄搜尋以確認索引目錄復原已成功完成。

