= 高效能索引
:allow-uri-read: 




=== 高效能索引

NetApp Backup and Recovery 引入了更新的索引功能，使來源系統上的資料索引更有效率。新的索引功能包括 UI 的更新、資料復原搜尋和復原方法效能的改進、全域搜尋功能的升級以及更好的可擴充性。

以下是改進的具體內容：

* *資料夾合併*：更新後的版本使用包含特定標識符的名稱將資料夾分組在一起，使索引過程更加順暢。
* *Parquet 檔案壓縮*：更新的版本減少了用於索引每個磁碟區的檔案數量，簡化了流程並消除了對額外資料庫的需求。
* *透過更多會話進行擴展*：新版本增加了更多會話來處理索引任務，從而加快了進程。
* *支援多個索引容器*：新版本使用多個容器來更好地管理和分配索引任務。
* *分割索引工作流程*：新版本將索引流程分為兩部分，提高了效率。
* *改進的並發性*：新版本可以同時刪除或移動目錄，從而加快索引過程。


.誰能從此功能中受益？
所有新客戶均可使用新的索引功能。

.如何啟用索引？
在使用搜尋和復原方法還原資料之前，您需要在計劃復原磁碟區或檔案的每個來源系統上啟用「索引」。這使得索引目錄可以追蹤每個捲和每個備份文件，從而使您的搜尋快速且有效率。

執行搜尋和還原時，透過選擇「啟用索引」選項在來源工作環境上啟用索引。

有關詳細信息，請參閱文檔 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["如何使用「搜尋和還原」還原ONTAP數據"]。

.支持規模
新的索引功能支援以下內容：

* 3分鐘內即可實現全球搜尋效率
* 最多 50 億個文件
* 每個集群最多 5000 個卷
* 每個磁碟區最多 10 萬個快照
* 基線索引的最長時間少於 7 天。實際時間將根據您的環境而有所不同。




=== 全域搜尋效能改進

此版本還包括對全域搜尋效能的增強。現在您將看到進度指示器和更詳細的搜尋結果，包括文件數量和搜尋所花費的時間。專用的搜尋和索引容器可確保全域搜尋在五分鐘內完成。

請注意與全域搜尋相關的以下注意事項：

* 新索引不會在標記為每小時的快照上執行。
* 新的索引功能僅適用於 FlexVols 上的快照，而不適用於 FlexGroups 上的快照。

