= UI改進
:allow-uri-read: 




=== UI改進

此版本透過簡化介面來增強您的體驗：

* 從卷宗表中刪除聚合列，以及從 V2 儀表板中的捲表中刪除快照策略、備份策略和複製策略列，可實現更簡化的佈局。
* 從下拉清單中排除未啟動的工作環境可以使介面更簡潔、導航更有效率、更快載入。
* 雖然標籤列的排序功能已停用，但您仍然可以查看標籤，確保重要資訊仍然易於存取。
* 刪除保護圖示上的標籤有助於使外觀更清晰並減少載入時間。
* 在工作環境啟動過程中，對話方塊會顯示載入圖示以提供回饋，直到發現過程完成，從而增強系統操作的透明度和信心。




=== 增強型音量儀表板（預覽版）

音量儀表板現在可在 10 秒內加載，提供更快、更有效率的介面。此預覽版可供部分客戶使用，讓他們可以事先了解這些改進。



=== 支援第三方 Wasabi 物件儲存（預覽版）

NetApp Backup and Recovery現在將其支援擴展到第三方物件存儲，主要專注於 Wasabi。此新預覽功能可讓您利用任何與 S3 相容的物件儲存來滿足您的備份和復原需求。



==== 開始使用 Wasabi

要開始使用第三方存儲作為物件存儲，您必須在控制台代理中啟用一個標誌。然後，您可以輸入第三方物件儲存的連接詳細資訊並將其整合到備份和還原工作流程中。

.步驟
. 透過 SSH 進入您的連接器。
. 進入NetApp Backup and Recovery cbs 伺服器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 打開 `default.json`文件裡面 `config`透過 VIM 或任何其他編輯器資料夾：
+
[listing]
----
vi default.json
----
. 調整 `allow-s3-compatible`：假 `allow-s3-compatible`： 真的。
. 儲存更改。
. 從容器中退出。
. 重新啟動NetApp Backup and Recovery cbs 伺服器容器。


.結果
容器再次開啟後，開啟NetApp Backup and RecoveryUI。當您啟動備份或編輯備份策略時，您將看到新的供應商「S3 Compatible」與 AWS、Microsoft Azure、Google Cloud、 StorageGRID和ONTAP S3 等其他備份提供者一起列出。



==== 預覽模式限制

雖然此功能處於預覽狀態，但請考慮以下限制：

* 不支援自備水桶 (BYOB)。
* 不支援在策略中啟用 DataLock。
* 不支援在政策中啟用存檔模式。
* 僅支援本地ONTAP環境。
* 不支援MetroCluster 。
* 不支援啟用儲存桶級加密的選項。


在此預覽期間，我們鼓勵您在推出完整功能之前探索此新功能並提供有關與第三方物件儲存整合的回饋。
