= Hyper-V 工作負載增強功能
:allow-uri-read: 




=== Hyper-V 工作負載增強功能

在此版本中、Hyper-V 工作負載引入了以下增強功能：

* *保護 SAN 儲存設備上的 VM*：您現在可以保護 SAN 物件儲存設備上的 VM。
* *還原至備用位置增強功能*：現在可以從 SAN 儲存設備上的 VM 主要位置和次要位置還原至備用位置。
* *將檔案和資料夾還原至客體 VM*：您現在可以將主要儲存設備上快照中的檔案和資料夾還原至客體 Windows VM。此功能僅支援 CIFS VM。


有關保護 Hyper-V 工作負載的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["保護 Hyper-V 工作負載概述"]。



=== KVM 工作負載增強功能

在此版本中、KVM 工作負載引入了以下增強功能：

*還原至替代位置*：您現在可以將 KVM VM 還原至替代目的地（此功能現已正式推出）。

有關保護 KVM 工作負載的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["保護 KVM 工作負載概述"]。



=== Oracle Database 工作負載增強功能

在此版本中、Oracle Database 工作負載引進下列增強功能：

* *Oracle AI Database 26ai 支援*：NetApp Backup and Recovery 現已支援 Oracle AI Database 26ai。
* *備份驗證支援*：您現在可以設定備份原則，以自動驗證 Oracle 資料庫備份的完整性。


有關保護 Oracle Database 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["保護 Oracle 資料庫工作負載概述"]。



=== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進了以下增強功能：

* *跨資料存放區保護群組支援*：現在可以選擇在保護虛擬磁碟跨越多個資料存放區的虛擬機器時，保護群組的行為。
* *複製支援*：您現在可以從主要儲存設備和次要儲存設備建立虛擬機器快照的複製。


有關保護 VMware 工作負載的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。



=== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.05.1*：此版本包含 Trident Protect 26.05.1。
* *基於 VM 的應用程式就地還原*：現在您可以將基於 VM 的應用程式還原到原始命名空間和原始叢集。


有關保護 Kubernetes 工作負載的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。
