= 還原和容錯移轉作業期間的命名空間註釋和標籤
:allow-uri-read: 




== 還原和容錯移轉作業期間的命名空間註釋和標籤

在還原和容錯移轉期間，目的地命名空間標籤和註釋會更新以符合來源：來源中的金鑰會新增至目的地金鑰或覆寫目的地金鑰，而僅存在於目的地中的金鑰則保持不變。


NOTE: 在 Red Hat OpenShift 中，命名空間註解非常重要，因為它們可以確保還原的 Pod 獲得正確的安全內容限制和權限，使其能夠存取磁碟區並在沒有權限錯誤的情況下執行。如需更多資訊，請參閱 link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift 安全上下文約束文檔"^]。

設定 Kubernetes 環境變數

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
在還原或容錯移轉之前，以防止特定目的地命名空間註釋被覆寫。例如：

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: 在還原或容錯移轉期間， `restoreSkipNamespaceAnnotations` 和  `restoreSkipNamespaceLabels` 中指定的任何命名空間註釋和標籤都會從還原或容錯移轉作業中排除。請確保在初始 Helm 安裝期間配置這些設定。若要深入瞭解，請參閱  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["設定其他 Trident Protect Helm Chart 設定"]。

如果您使用 Helm 並帶有 `--create-namespace`旗標來安裝來源應用程式，Trident Protect 會將名稱標籤複製到目的地命名空間。如果標籤值與來源命名空間名稱相符，則會將其取代為目的地命名空間名稱；否則，則保持不變。



=== 範例

以下範例顯示具有不同標籤和註釋的來源命名空間和目的地命名空間，並顯示作業前後的目的地命名空間，以說明如何新增、合併或覆寫金鑰。



==== 在還原或容錯移轉作業之前

下表說明了復原或容錯移轉作業之前範例來源命名空間和目標命名空間的狀態：

[cols="1,2a,2a"]
|===
| 命名空間 | 註解 | 標籤 


| 命名空間 ns-1 （來源）  a| 
* annotation.one/key: 「updatedvalue」
* annotation.two/key: 「true」

 a| 
* environment=production
* 合規性＝hipaa
* 名稱=ns-1




| 命名空間 ns-2 （目標）  a| 
* annotation.one/key: 「true」
* annotation.three/key:「false」

 a| 
* 角色=資料庫


|===


==== 還原作業後

下表展示了復原或故障轉移作業後範例目標命名空間的狀態。一些鍵已被添加，一些鍵已被覆蓋，並且  `name` 標籤已更新以匹配目標命名空間：

[cols="1,2a,2a"]
|===
| 命名空間 | 註解 | 標籤 


| 命名空間 ns-2 （目標）  a| 
* annotation.one/key: 「updatedvalue」
* annotation.two/key: 「true」
* annotation.three/key:「false」

 a| 
* 名稱=ns-2
* 合規性＝hipaa
* environment=production
* 角色=資料庫


|===